scripts/update-registry/index.js
src/registry/registry.json

Updates the registry to 52.0
@W-9482574@

chore: update registry to 52.0

---

.github/CODEOWNERS
package.json
scripts/update-registry/index.js
src/client/index.ts
src/index.ts
src/registry/registry.json
test/client/metadataTransfer.test.ts
yarn.lock

Port `develop` changes to `main` for v3.1.0 release.

chore: port v3.1.0 to main

---

CHANGELOG.md

chore: changelog v3.1.0

---

.github/CODEOWNERS
package.json

chore: port #365 back to develop 

---

package.json

Merge package bump back to develop.

chore: updated version 3.1.0

---

CHANGELOG.md

chore: generated CHANGELOG for 3.1.1

---

.github/CODEOWNERS
package.json
src/registry/registry.json
test/client/metadataTransfer.test.ts
yarn.lock

Port develop to main for 3.1.1

Port pr v3.1.1

---

package.json

chore: updated version 3.1.1

---

CHANGELOG.md

chore: generated CHANGELOG for 4.0.0

---

package.json
src/client/types.ts

Adds the `RunTestResult` and its subtypes to types
@W-9622493@

fix: add RunTestResult type

---

src/convert/streams.ts
test/convert/streams.test.ts

Prevents writing invalid XML in metadata files of child types during stream writing.  If the code has already written to a file it will ignore a 2nd entry in the response.  This can happen with certain CustomObject ListViews such as Tasks due to a known server side bug (currently being fixed).
@W-9543558@
Invalid metadata XML written.  E.g., 
```
<ListView>
...
<filters>
<field>DUE_DATE</field>
<operation>equals</operation>
</filters>
<label>Unscheduled Tasks</label>
</ListView>
Tasks}</label>
</ListView>
```
Correct metadata XML written.

fix: ignore duplicate components in server response

---

src/client/types.ts

Reverts forcedotcom/source-deploy-retrieve#395

Revert "fix: add RunTestResult type"

---

src/registry/registry.json

Reverts forcedotcom/source-deploy-retrieve#389

Revert "chore: add CustomFieldTranslation to registry"

---

CHANGELOG.md

Changelog v4.0.1

---

CONTRIBUTING.md
HANDBOOK.md

This PR adds Bryan's SDR Handbook as a markdown document to this repo. As part of the work for this PR, internal-only discussion and information was separated from the document. The internal information can now be found at https://salesforce.quip.com/NEs5AiGgL219. The contents of that file will replace the current SDR Handbook document once this PR is approved. 
@W-9642878@
The SDR Handbook was only visible to those with access to the Quip document.
The SDR Handbook is visible to anyone viewing this repo.

feat: added SDR Handbook to the repo

---

src/convert/transformers/staticResourceMetadataTransformer.ts

set compression level for static resource consistent with toolbelt
@W-9679677@ https://github.com/forcedotcom/cli/issues/1098

fix: static resource size consistency

---

CHANGELOG.md

chore: generated CHANGELOG for 4.0.2

---

CONTRIBUTING.md
HANDBOOK.md
src/convert/transformers/staticResourceMetadataTransformer.ts
src/resolve/adapters/bundleSourceAdapter.ts
test/mock/registry/mockRegistry.ts
test/mock/registry/type-constants/bundleConstants.ts
test/resolve/adapters/bundleSourceAdapter.ts

Port pr v4.0.2

---

package.json

chore: updated version 4.0.2

---

CHANGELOG.md

chore: generated CHANGELOG for 4.1.0

---

.circleci/config.yml
README.md
package.json
src/collections/componentSet.ts
src/collections/types.ts
src/convert/metadataConverter.ts
src/convert/streams.ts
src/resolve/adapters/baseSourceAdapter.ts
src/resolve/adapters/decomposedSourceAdapter.ts
src/resolve/sourceComponent.ts
test/collections/componentSet.test.ts
test/convert/metadataConverter.test.ts
test/convert/streams.test.ts
test/resolve/adapters/decomposedSourceAdapter.ts
test/resolve/sourceComponent.test.ts
typedoc.json

Port pr v4.1.0

---

CHANGELOG.md

chore: generated CHANGELOG for 4.0.3

---

package.json
src/resolve/forceIgnore.ts
test/resolve/forceIgnore.test.ts
yarn.lock

chore: remove support for old .forceignore file format

---

package.json
yarn.lock

update @salesforce/core to 2.28.0
@W-9955035@

chore: update sfdx-core to 2.28.0

---

src/registry/registry.json

feat: support epb types

---

src/registry/metadataRegistry.json

Reverts forcedotcom/source-deploy-retrieve#502

Revert "feat: support new OmniScript and OmniIntegrationProcedure type"

---

package.json
yarn.lock

bump version of `@salesforce/core`
@W-8776235@

feat: update version of core

---

.circleci/config.yml
.github/dependabot.yml

Enables dependabot job
@W-8776236@
No dependabot
Dependabot job enabled with automerge (squash) when a PR passes all checks.

chore: enable dependabot

---

.github/CODEOWNERS

Update CODEOWNERS with GUSINFO of PDT and CLI teams
@W-9377468@
N/A
No change in functionality

Update CODEOWNERS with GUSINFO

---

src/resolve/forceIgnore.ts
test/resolve/forceIgnore.test.ts

when the `.forceignore` finds a `\` it will warn the user that that format will no longer be supported, and will change it so that it'll work for them
@W-10464641@
with `force-app\main\default\classes\post.*` in the `.forceignore`, `sfdx force:source:deploy -p force-app/main/default/classes`
```
DEPLOY PROGRESS | ████████████████████████████████████████ | 8/8 Components
=== Deployed Source
FULL NAME                 TYPE       PROJECT PATH
────────────────────────  ─────────  ────────────────────────────────────────────────────────────────────
GeocodingService          ApexClass  force-app/main/default/classes/GeocodingService.cls
...
post                      ApexClass  force-app/main/default/classes/post.cls
post                      ApexClass …
```

fix: warn and convert on windows seps in .forceignore

---

METADATA_SUPPORT.md
src/registry/metadataRegistry.json

Add a new UiViewDefinition type to the Metadata Registry
@W-10495831@
sfdx force:source commands did not work for UiViewDefinition type
sfdx force:source commands work for UiViewDefinition type

rohitachar/ add new UiViewDefinition metadata type to registry

---

contributing/metadata.md

Adds documentation for steps of registering metadata entity.
NA

docs: adds steps for updating registry and local setup rev@mshanemc

---

src/registry/metadataRegistry.json

Adds support for BotTemplate type to sfdx cli
@W-10400626@
source commands did not work for BotTemplate
source commands work for BotTemplate

feat(metadata registry): adding BotTemplate to metadata registry

---

.circleci/config.yml

the zip fix, but without commits from the perf nuts confusing git during the release

feat: don't run nuts on release/main

---

package.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8370C-CPU-2-80GHz/eda.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8370C-CPU-2-80GHz/lotsOfClasses.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8370C-CPU-2-80GHz/lotsOfClassesOneDir.json
yarn.lock

bumps core to include redirect fix from jsforce/sfdx-core
@W-0@

fix: bump core

---

package.json
test/client/metadataApiDeploy.test.ts
test/client/metadataApiRetrieve.test.ts
test/client/metadataTransfer.test.ts
test/collections/componentSet.test.ts
test/convert/metadataConverter.test.ts
test/convert/transformers/decomposedMetadataTransformer.test.ts
test/convert/transformers/nonDecomposedMetadataTransformer.test.ts
test/mock/client/index.ts
test/mock/client/transferOperations.ts
test/nuts/perfResults/x64-linux-2xIntel-Xeon-CPU-E5-2673-v3-2-40GHz/eda.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-CPU-E5-2673-v3-2-40GHz/lotsOfClasses.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-CPU-E5-2673-v3-2-40GHz/lotsOfClassesOneDir.json
test/resolve/connectionResolver.test.ts
yarn.lock

Use `TestContext` from https://github.com/forcedotcom/sfdx-core/pull/676
@W-11884373@

chore: use TestContext

---

src/registry/metadataRegistry.json

Adds support for BotBlock type to sfdx cli
@W-11156416@
source commands did not work for BotBlock
source commands work for BotBlock

feat(metadata registry):  adding BotBlock to metadata registry

---

METADATA_SUPPORT.md
src/registry/metadataRegistry.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8370C-CPU-2-80GHz/eda.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8370C-CPU-2-80GHz/lotsOfClasses.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8370C-CPU-2-80GHz/lotsOfClassesOneDir.json

MAE wasn't recognized
convert/deploy/retrieve works

fix: fix MAE suffix

---

.github/workflows/failureNotifications.yml
.github/workflows/test.yml
test/nuts/perfResults/x64-linux-2xIntel-Xeon-CPU-E5-2673-v3-2-40GHz/eda.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-CPU-E5-2673-v3-2-40GHz/lotsOfClasses.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-CPU-E5-2673-v3-2-40GHz/lotsOfClassesOneDir.json

[@W-11976301@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-11976301)

Sync files

---

METADATA_SUPPORT.md
src/registry/metadataRegistry.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8272CL-CPU-2-60GHz/eda.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8272CL-CPU-2-60GHz/lotsOfClasses.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8272CL-CPU-2-60GHz/lotsOfClassesOneDir.json

Enable CLI support for ExtlClntAppGlobalOauthSettings
[W-12721422](https://gus.lightning.force.com/a07EE00001NblxOYAR)
sfdx force:source and force:mdapi commands didn't support MD type for ExtlClntAppGlobalOauthSettings
sfdx force:source and force:mdapi commands supports MD type for ExtlClntAppGlobalOauthSettings

Enable CLI support for ExtlClntAppGlobalOauthSettings

---

.github/workflows/supportedMetadataUpdate.yml
METADATA_SUPPORT.md
test/nuts/perfResults/x64-linux-2xIntel-Xeon-CPU-E5-2673-v4-2-30GHz/eda.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-CPU-E5-2673-v4-2-30GHz/lotsOfClasses.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-CPU-E5-2673-v4-2-30GHz/lotsOfClassesOneDir.json

removes one type from mdSupport so that automated script can put it back in.  hopefully

ci: automate md support doc 

---

package.json
yarn.lock

bump dev-scripts to get `yarn docs` script fix
found during QA of @W-12776876@

fix: bump dev-scripts to avoid deleting perf data

---

package.json
src/client/metadataTransfer.ts
yarn.lock

another connection issue to retry
https://github.com/forcedotcom/cli/issues/2086
@W-13147788@

fix: another connection error

---

package.json
src/registry/metadataRegistry.json
src/registry/nonSupportedTypes.ts
yarn.lock

https://github.com/forcedotcom/source-deploy-retrieve/actions/runs/4953010039/jobs/8860023200

feat: support for UserAccessPolicy

---

.github/workflows/perfScaleNut.yml

uses sf, not sfdx, for scale nuts

test: use sf for perf/scale nuts

---

.github/workflows/perfScaleNut.yml
package.json
yarn.lock

fix: bump core to latest

---

src/registry/stdValueSetRegistry.json

Add support for the AQLMUFInterval StandardValueSet

fix: add AQLMUFInterval StandardValueSet

---

contributing/metadata.md
scripts/update-registry/update2.ts
src/registry/metadataRegistry.json
src/registry/nonSupportedTypes.ts

2 new types: ServiceProcess and ProcessFlowMigration
use sf and new styles for scripts and registry contribution docs
[@W-13753987@](https://gus.lightning.force.com/a07EE00001W3OQkYAN)

feat(md-types): ServiceProcess and ProcessFlowMigration

---

METADATA_SUPPORT.md
scripts/update-registry/update-supported-metadata.ts
src/registry/coverage.ts

Skipping v60 for now, it is not working
Added new endpoints for collecting metadata coverage
Hopefully fixed table markdown rendering

md coverage and updated endpoints

---

src/registry/metadataRegistry.json
src/registry/nonSupportedTypes.ts

Adds support for more metadata types
https://github.com/forcedotcom/cli/issues/2527
@W-14416331@

fix: add support for more metadata types

---

src/registry/metadataRegistry.json

The PR add to the registry 3 new entities for Service Catalog Eligibility Rules.
GUS Item
@W-14580625@

Adding 3 entities for Service Catalog Eligibility Rules

---

LICENSE.txt
src/resolve/connectionResolver.ts

resolve a potential unhandled promise exception
https://github.com/forcedotcom/eslint-config-salesforce-typescript/actions/runs/7390721054/job/20106191425?pr=210

refactor: fix no-floating-promises linter rule

---

contributing/metadata.md

Replaces references to plugin-source with plugin-deploy-retrieve

chore: Update metadata.md

---

src/registry/metadataRegistry.json
src/registry/nonSupportedTypes.ts

Adds ExpressionSetObjectAlias metadata type
@W-14600356@

fix: add the ExpressionSetObjectAlias metadata type

---

test/nuts/local/replacements/replacementsLabels.nut.ts
test/nuts/local/replacements/testProjWithLabels/config/project-scratch-def.json
test/nuts/local/replacements/testProjWithLabels/force-app/main/default/classes/replaceStuff.cls
test/nuts/local/replacements/testProjWithLabels/force-app/main/default/classes/replaceStuff.cls-meta.xml
test/nuts/local/replacements/testProjWithLabels/force-app/main/default/labels/CustomLabels.labels-meta.xml
test/nuts/local/replacements/testProjWithLabels/force-app/main/default/objects/TestObj__c/TestObj__c.object-meta.xml
test/nuts/local/replacements/testProjWithLabels/force-app/main/default/objects/TestObj__c/fields/FieldA__c.field-meta.xml
test/nuts/local/replacements/testProjWithLabels/force-app/main/default/staticresources/Test.resource-meta.xml
test/nuts/local/replacements/testProjWithLabels/force-app/main/default/staticresources/Test/folder/test2.css
test/nuts/local/replacements/testProjWithLabels/force-app/main/default/staticresources/Test/test.css
test/nuts/local/replacements/testProjWithLabels/label.txt
test/nuts/local/replacements/testProjWithLabels/replacements.txt
test/nuts/local/replacements/testProjWithLabels/sfdx-project.json

adds a local nut test for the intersection of custom labels and replacements
not a fix, but a "assurance correctness" for https://github.com/forcedotcom/cli/issues/2675
I want to see this run on windows, too, since the user is

test: nut for customLabels replacements

---

src/registry/metadataRegistry.json

Reverts forcedotcom/source-deploy-retrieve#1160

fix: revert deployment of ESVersion,DMVersion

---

.github/workflows/supportedMetadataUpdate.yml

Updates the `.github/workflows/supportedMetadataUpdate.yml` file to pass in git config username and email
Part of [@W-14809762@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-14809762)

GitConfig changes

---

src/registry/metadataRegistry.json

Update metadata registries for mlmodelartifact, mlmodelconnection and mlmodelschema top level components
@W-15020853@

@W-15020853 Update metadata registries for mlmodelartifact, mlmodelconnection and mlmodelschema top level components

---

src/registry/variants.ts

was swallowing errors from bad presets.
will also throw when the registryCustomizations are bad (ex: bad json)

fix: throw on bad presets

---

src/registry/metadataRegistry.json

fix: suffix mismatch

---

contributing/metadata.md

Update Slack links

---

scripts/update-registry/update2.ts
src/registry/metadataRegistry.json
src/registry/nonSupportedTypes.ts

new mdTypes
- ForecastingGroup
- SearchCustomization
- SearchOrgWideObjectConfig
- RetrievalSummaryDefinition
[@W-15691863@](https://gus.lightning.force.com/a07EE00001qlHRQYA2)

feat(mdTypes): ForecastingGroup, SearchCustomization, SearchOrgWideObjectConfig, RetrievalSummaryDefinition

---

src/registry/metadataRegistry.json
src/registry/nonSupportedTypes.ts

feat(mdTypes): add support for genAiFunction, genAiPlanner

---

src/registry/metadataRegistry.json

Add new datakit entity datakitobjectdependency

---

.github/workflows/releaseWithCoreBundle.yml
.github/workflows/testWithCoreBundle.yml

Automate the release and test with core-bundle
@W-15634780@
No automation test against core-bundle and there is only manual release of sdr-bundle
Automation of the release and test of sdr-bundle

chore: add automation of release and test workflow

---

package.json
yarn.lock

fix(deps): bump kit et al

---

package.json
yarn.lock

feat!(deps): core8

---

package.json
src/collections/decodeableMap.ts
test/collections/decodeableMap.test.ts
yarn.lock

adjust decodeableMap test to avoid constructor

test(deps): bump dev-scripts

---

package.json

feat: bump to 12.3.0

---

src/registry/metadataRegistry.json

needed for DF for Phillipe Ozil, who is going to QA and respond by end of Aug20 on whether it solves the issues
[@W-16540802@](https://gus.lightning.force.com/a07EE00001zQVzkYAG)

genAiFunction changes structure to be a bundle

---

.github/workflows/onRelease.yml
.github/workflows/releaseWithCoreBundle.yml

- Adds a check to skip publish job if it's a beta release
@W-16304265@

chore: modify workflows to skip publish upon beta release

---

src/registry/metadataRegistry.json

#<Insert GitHub Issue>, @<Insert GUS WI>@ [skip-validate-pr]

fix: adding new saml plugin to eca

---

src/registry/metadataRegistry.json

This PR registers three metadata types as part of TUA: AnalyticsVisualization, AnalyticsVizViewDef, and AnalyticsWorkspace.
https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE0000243IzcYAE/view
@W-17064228@

feat(mdTypes): Register TUA Visualization and Workspace metadata types

---

src/registry/presets/decomposeSharingRulesBeta.json
test/snapshot/sampleProjects/preset-sharingRules/__snapshots__/verify-md-files.expected/package.xml

sharing rule children are now addressable in the beta preset
@W-17572243@

fix: sharing rule children are now addressable in the beta preset

---

METADATA_SUPPORT.md
scripts/update-registry/describe.json
src/registry/metadataRegistry.json
src/resolve/metadataResolver.ts
src/utils/filePathGenerator.ts

This PR registers new metadata types LightningTypes.
@W-16967399@
https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000023E6XyYAK/view

feat: custom lightning types support

---

src/registry/metadataRegistry.json

To match the updated directory name for AnalyticsWorkspace, we need to match the metadata registry
@W-17404777 

@W-17404777 Update metadataRegistry.json to match Analytics Workspace

---

src/registry/metadataRegistry.json

@W-17693203 Remove aiEvaluationTestSet from metadataRegistry

---

src/utils/filePathGenerator.ts
test/snapshot/sampleProjects/genAiFunctions/__snapshots__/verify-md-files.expected/genAiFunctions/CustomKnowledgeAction_1738700253695/CustomKnowledgeAction_1738700253695.genAiFunction-meta.xml
test/snapshot/sampleProjects/genAiFunctions/__snapshots__/verify-md-files.expected/genAiFunctions/CustomKnowledgeAction_1738700253695/input/schema.json
test/snapshot/sampleProjects/genAiFunctions/__snapshots__/verify-md-files.expected/genAiFunctions/CustomKnowledgeAction_1738700253695/output/schema.json
test/snapshot/sampleProjects/genAiFunctions/__snapshots__/verify-md-files.expected/package.xml
test/snapshot/sampleProjects/genAiFunctions/__snapshots__/verify-source-files.expected/force-app/main/default/genAiFunctions/CustomKnowledgeAction_1738700253695/CustomKnowledgeAction_1738700253695.genAiFunction-meta.xml
test/snapshot/sampleProjects/genAiFunctions/__snapshots__/verify-source-files.expected/force-app/main/default/genAiFunctions/CustomKnowledgeAction_1738700253695/input/schema.json
test/snapshot/sampleProjects/genAiFunctions/__snapshots__/verify-source-files.expected/force-app/main/default/genAiFunctions/CustomKnowledgeAction_1738700253695/output/schema.json
test/snapshot/sampleProjects/genAiFunctions/originalMdapi/genAiFunctions/CustomKnowledgeAction_1738700253695/CustomKnowledgeAction_1738700253695.genAiFunction-meta.xml
test/snapshot/sampleProjects/genAiFunctions/originalMdapi/genAiFunctions/CustomKnowledgeAction_1738700253695/input/schema.json
test/snapshot/sampleProjects/genAiFunctions/originalMdapi/genAiFunctions/CustomKnowledgeAction_1738700253695/output/schema.json
test/snapshot/sampleProjects/genAiFunctions/sfdx-project.json
test/snapshot/sampleProjects/genAiFunctions/snapshot.test.ts
test/utils/filePathGenerator.test.ts

#https://github.com/forcedotcom/cli/issues/3204, @W-17750901@

fix: add genAiFunction bundle type W-17750901

---

src/registry/metadataRegistry.json

Add analytics Dashboard to metadata registry
To support 2GP managed packaging
@W-17810536@

W-17810536 - fix: Add analytics Dashboard to metadata registry

---

package.json
src/resolve/connectionResolver.ts

Replaces the code pattern `array.push(...otherArray)` with `array.concat(otherArray)` for reduced memory consumption.
@W-18033709@

W-18033709 - fix: use concat rather than array spreading

---

src/registry/metadataRegistry.json
src/utils/filePathGenerator.ts

Adds support for GenAiPlannerBundle metadata
@W-18203471@

W-18203471 - fix: add support for GenAiPlannerBundle

---

src/registry/metadataRegistry.json

fix dataobjectbuildorgtemplate

---

src/client/types.ts

adds new state from server to deploy status type
@W-19159018@

fix: add new deploy status W-19159018
