forcedotcom/source-deploy-retrieve

package.json
test/client/metadataTransfer.test.ts
yarn.lock

Bump the version of @salesforce/core to 2.24.1 to get a fix for the PollingClient.  Fix and write more unit
tests to guard against regressions.
@W-9505934@
The PollingClient from the `@salesforce/core` library had a bug that was not awaiting the result of the polling function before the setInterval timer would call the polling function again.  This was causing larger metadata retrieves to throw an error because the request would complete but the polling would send another request to the server and that extra request(s) would cause an error.
The fixed PollingClient in the core library now properly waits for the polling function to return before polling again.

fix: bump the version of @salesforce/core for PollingClient fix

---

.github/CODEOWNERS
package.json

The package.json version was incorrect when last publishing the library. This resets it back to `3.0.0` so when the job runs, it will properly bump to `3.1.0`.
It also fixes an issue with having multiple codeowners.
@W-9544572@

fix: codeowners syntax and package version

---

src/registry/registry.json

Add `WaveComponent` to metadata registry here so deploy and retrieve work.
`WaveComponent` works like `WaveDashboard` since it's an extension of `WaveDashboard`.
@W-9520846@
Currently, deploy and retrieve on `WaveComponent` returns error from this library and plugins-source.
It works, tested via `resolve('/path/to/wave/file.comp')` and when linked into plugins-source linked into sfdx.

fix: add WaveComponent to metadata registry

---

package.json
test/client/metadataTransfer.test.ts
yarn.lock

bumps core to get a PollingClient fix.  The library used by the PollingClient in core would default to a max poll retries of 10 rather than poll until a timeout is reached.  The fix in core was to specify an option to poll infinite retries (but stop if a timeout is hit).
@W-9545459@
Large deploys or retrieves would cause an error to be thrown after 10 polling attempts.
Polling will run until the timeout.

fix: bumps the version of core to 2.25.1

---

.github/CODEOWNERS

adds platform-cli team to codeowners

chore: update CODEOWNERS with CLI team

---

package.json
src/client/metadataApiRetrieve.ts
src/client/types.ts
test/client/metadataApiRetrieve.test.ts
test/collections/componentSet.test.ts
test/mock/client/transferOperations.ts

when retrieving with packagenames, it will place their metadata into their respective package.  The location of the package metadata can also be changed by defining `PackageOptions.outputDir` as part of the retrieve options, which is what the VS Code extension would use.
NOTE: this is a breaking change and will require a major version bump since the name of `RetreiveOptions.packageNames` was changed to `RetrieveOptions.packages`, which is a better name given the changed type of that option.
@W-9252107@
before all the metadata was placed under the default package
the metadata is placed into the expected package dir

fix: retrieve package names to their respective packages

---

src/resolve/metadataResolver.ts
test/resolve/metadataResolver.test.ts

Changes MetadataResolver.resolveComponent() to check if all paths are forceignored (including directories) rather than just metadata files before resolution so that errors aren't thrown in certain cases (see below).
This PR is courtesy of @jayree.  Thank you!
@W-9543674@
With `.forceignore` contents that include an entry of `**/test1`, which should ignore test1 directories the following command would cause an error:
`sfdx force:source:retrieve -p force-app`
ERROR running force:source:retrieve:  Metadata xml file unpackaged/experiences/test1.site-meta.xml is forceignored but is required for unpackaged/experiences/test1
No error is thrown for the same command and the same `.forceignore` contents

fix: resolveComponent no longer tries to resolve ignored dir paths

---

src/registry/registry.json

Add BatchCalcJobDefinition to metadata registry
A customer tried to retrive the component using sfdx source retrive from VS Code extension and received error "Missing metadata type definition in registry for id 'batchcalcjobdefinition'"
@W-9589556@
Retrieve fails through vs code extension
Retrieve succeeds through vs code extension

Add BatchCalcJobDefinition to metadata registry

---

scripts/update-registry/typeOverride.json
src/registry/registry.json
src/resolve/metadataResolver.ts

This PR goes against the [handbook](https://salesforce.quip.com/F3q6AmNSquvE#ZJKACAn1eZP) but enabling this type for a retrieve which would have required adding a new Transfomer/adapter, which would also go against the [handbook](https://salesforce.quip.com/F3q6AmNSquvE#ZJKACABWVSO)
this approach seemed a little better
all credit goes to @jayree
@W-9543539@
`EmailServicesFunction` wasn't able to be retrieved
`EmailServicesFunction` able to be retrieved

chore: enable EmailServicesFunction

---

src/client/metadataApiDeploy.ts
src/client/metadataTransfer.ts
src/collections/componentSet.ts
src/convert/metadataConverter.ts
test/client/metadataApiDeploy.test.ts
test/collections/componentSet.test.ts
test/convert/metadataConverter.test.ts
test/mock/client/transferOperations.ts

Adds the ability to set the manifest version from a ComponentSet.  This is necessary to support source that is in a format specific to an API version.  Also overloads the MetadataConverter.convert() method to take a ComponentSet or list of Components.
@W-9604681@
It was not possible to change the version within the generated manifest for a deploy or retrieve
The `sourceApiVersion` within a sfdx-project.json can be used to change the generated manifest version.

fix: add support for sourceApiVersion

---

src/registry/registry.json

Adds `CustomFieldTranslation` type, courtesy of @jayree
https://github.com/jayree/source-deploy-retrieve/commit/f66a025df1b1a2ce825f660c2144ef093e0c3c2c

chore: add CustomFieldTranslation to registry

---

src/registry/registry.json

Adds missing metadata types to the registry that toolbelt supported
@W-9604298@
SDR would throw an error `Missing metadata type definition in registry for id 'dynamictrigger'`
SDR should be able to work with the type

fix: add missing types from toolbelt to the best of my ability

---

src/registry/registry.json

Adds missing metadata types to the registry that toolbelt supported
to `develop` branch
@W-9604298@
Functionality Before
SDR would throw an error Missing metadata type definition in registry for id 'dynamictrigger'
Functionality After
SDR should be able to work with the type

chore: add types to the best of my ability 2

---

src/resolve/adapters/bundleSourceAdapter.ts
test/mock/registry/type-constants/bundleConstants.ts
test/resolve/adapters/bundleSourceAdapter.ts

if a there was an empty top level directory for a bundle type, I'll use LWC as an example, it would cause deploy errors. I filter those out during the bundle adapter's `populate` method
so a `force:source:deploy -m LightningComponentBundle`
on a dir that looks like 
```   * lwc/
* ├── validLWC/
* |   ├── myFoo.js
* |   ├── myFooStyle.css
* |   ├── myFoo.html
* |   ├── myFoo.js-meta.xml
* ├── invalidLWC/
```
will only result in `validLWC` being deployed, and no errors
#https://github.com/forcedotcom/cli/issues/1099, @W-9692466@
error on the server `An object 'withoutContent' of type LightningComponentBundle was named in package.xml, but was not found in zipped directory`
deploys correctly

chore: invalid empty bundle types filtered from result

---

src/resolve/adapters/baseSourceAdapter.ts
src/resolve/adapters/decomposedSourceAdapter.ts
test/resolve/adapters/decomposedSourceAdapter.ts

the `decomposedSourceAdapter` was calling `baseSourceAdapter.getComponents` which was throwing an error when a parent xml file wasn't found or was .forceignore'd
this wasn't working for decomposed types because the parent isn't required... and so it was throwing when it shouldn't - blocking functionality. 
I overrode  the `getComponents` in the `decomposedSourceAdapter` adapter so that it wouldn't throw an error in that scenario
https://github.com/forcedotcom/cli/issues/1110, https://github.com/forcedotcom/cli/issues/1106, @W-9720135@
```
Metadata xml file /Users/william.ruemmele/projects/scratches/SFDXCLI-Issues/CLIIssues/force-app/main/default/objects/hed__Term__c/hed__Term__c.object-meta.xml is forceignored but is required for …
```

fix: getComponent won't throw when parent is ignored

---

src/collections/componentSet.ts
src/collections/types.ts
src/convert/metadataConverter.ts
src/convert/streams.ts
src/resolve/sourceComponent.ts
test/collections/componentSet.test.ts
test/convert/metadataConverter.test.ts
test/convert/streams.test.ts
test/resolve/sourceComponent.test.ts

Adds support to the library for building ComponentSets that contain components marked for delete. Deploying these ComponentSets will build a destructive changes manifest so they are deleted in the org. If any components not marked for delete are included they are deployed as well.
@W-9478450@
Functionality Before
unsupported
Functionality After
ComponentSets can be created with a set of components marked for delete, or a mix of regular components and components to be deleted. This ComponentSet can then be deployed as usual and metadata can be deleted.
```javascript
ComponentSet.fromSource({
fsPaths: [path/to/changed/files],
fsDeletedPaths: [path/to/deleted/files]
}).deploy();
const components = …
```

feat: adds support for destructive changes

---

src/registry/registry.json

Updates the registry to define a strictDirectoryName for the RestrictionRule type since the suffix ("rule") is also used by the ModerationRule type.
https://github.com/forcedotcom/cli/issues/1158
@W-9833678@
Source is converted to metadata API format with a moderation folder instead of restrictionRules. The package.xml file also defines the metadata type as ModerationRule instead of RestrictionRule.
Source is converted to metadata API format with a restrictionRules folder and the package.xml should reference the RestrictionRule metadata type.

fix: force RestrictionRule to a strict directory

---

src/convert/transformers/staticResourceMetadataTransformer.ts

fixes an Error message parsing issue with differences between `node 14` and `node 16`
`Cannot read properties of undefined (reading 'contentType')`
`A StaticResource must have an associated .resource file, missing staticresources/a.resource-meta.xml`

fix: fix node 16 error parsing issue

---

src/registry/registry.json

fixes the `FunctionsReference` type suffix it should be singular `function` but it was `functions` in the suffix object
would resolve `FunctionReference` to `EmailServicesFunctions`
will properly deploy a `FunctionReference`

fix: fix functions to function suffix

---

src/registry/registry.json

Updates the registry for ManagedTopics so that ManagedTopic children will not be included in the manifest during a source convert.
https://github.com/forcedotcom/cli/issues/1192
@W-9910605@
errors with: `An object 'topicName' of type ManagedTopic was named in package.xml, but was not found in zipped directory.`
success

fix(registry.json): registry update for ManagedTopics

---

src/resolve/manifestResolver.ts
test/mock/registry/manifestConstants.ts
test/resolve/manifestResolver.test.ts

Reset the type after each manifest member entry.  Fixes the recent regression.  Note however that nested inFolder type metadata is still not supported properly but will be asap.
https://github.com/forcedotcom/cli/issues/1165
https://github.com/forcedotcom/cli/issues/1180
@W-9882522@
Deploy Error:
An  object  'emailTemplateDir/emailTemplateName' of  type EmailTemplate was named in package.xml, but was not found in zipped  directory
Successful convert and deploy

fix: better support for non-nested inFolder types

---

src/convert/convertContext.ts
test/convert/convertContext.test.ts
test/mock/registry/type-constants/decomposedConstants.ts

previously, child types would be written with `xmlns="http://soap.sforce.com/2006/04/metadata"` attribute in metadata format, this was unnecessary and made the xml harder to read
mdapi-convereted files won't write child types with that attribute
https://github.com/forcedotcom/cli/issues/1142, @W-9803903@
```
<compactLayouts xmlns="http://soap.sforce.com/2006/04/metadata">
<fullName>Broker_Compact</fullName>
<fields>Name</fields>
<fields>Title__c</fields>
<fields>Phone__c</fields>
<fields>Mobile_Phone__c</fields>
<fields>Email__c</fields>
<label>Broker Compact</label>
</compactLayouts>
```
in dreamhouse-lwc, `sfdx force:source:convert -d output -m CustomObject` 
check `output/objects/Broker__c.object`
```
<compactLayouts>
<fullName>Broker_Compact</fullName> …
```

fix: remove XML_NS_KEY from children when written in metadata format

---

src/resolve/metadataResolver.ts
test/resolve/metadataResolver.test.ts

Fixes a bug with resolving in-folder folder types on windows in mdapi format.
@W-9739746@
In-folder folder types (reportFolder, emailFolder, etc.) would resolve to emailServices on Windows
In-folder folder types resolve to the proper type on Windows.

fix: resolve folderContentTypes in mdapi format for windows

---

src/resolve/adapters/decomposedSourceAdapter.ts
test/resolve/adapters/decomposedSourceAdapter.ts

If a CustomFieldTranslation was resolved before the parent CustomObjectTranslation it would not set the parent SourceComponent content, which caused problems during transformation.
@W-9946398@
Doesn't convert the field translations properly
CustomFieldTranslations are converted properly

fix: resolve CustomFieldTranslations properly

---

src/collections/componentSet.ts
src/registry/registry.json
src/registry/types.ts
test/collections/componentSet.test.ts

prior, `sObjects` and `CustomObjects` weren't able to be retrieved because the defined `sObject` would be overwritten by a wildcard
now manifests can contain wildcards and named elements for types that support it with the new registry option. Which is only `CustomObjects` for now
https://github.com/forcedotcom/cli/issues/1205, @W-9960907@
```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">;
<types>
<members>Account</members>
<name>CustomObject</name>
</types>
<types>
<members>*</members>
<name>CustomObject</name>
</types>
<version>53.0</version>
</Package>
```
would only retrieve the `CustomObjects`
retrieves all `CustomObjects` and the sObject `Account`

fix: support mixed wildcards and names in manifests

---

src/resolve/sourceComponent.ts
test/convert/convertContext.test.ts
test/mock/registry/mockRegistry.ts
test/resolve/sourceComponent.test.ts

fix `sourceComponent.parseXml()` for childComponents
@W-10031154@
`sourceComponent.parseXml()` returns full xml content of the parentComponent for childComponents
`sourceComponent.parseXml()` returns only childComponent xml content

childComponent xml data is not parsed correctly

---

README.md

Make it possible to use this library with link to current detailed docs.
(None)
The example on README did not work. The links to API docs was confounding, also had outdated examples.
The HANDBOOK is clearly the best docs here, so make it obvious.

Replace the outdated usage example code and links with HANDBOOK

---

src/registry/metadataRegistry.json
src/resolve/metadataResolver.ts

makes sitedotcom strictDir
https://salesforce-internal.slack.com/archives/C01LKDT1P6J/p1636049318137700
ERROR running force:source:convert:  /home/circleci/ci_app/force-app/main/default/sites/IdeaExchange.site-meta.xml: Expected source files for type 'SiteDotCom'

fix: unconfuse sitedotcom vs site

---

src/registry/metadataRegistry.json

Adds source tracking for metadata object: OmniScript and OmniIntegrationProcedure
@W-10181500@
sfdx force:source commands did not work for OmniScript and OmniIntegrationProcedure
sfdx force:source commands should work for OmniScript and OmniIntegrationProcedure

feat: support new OmniScript and OmniIntegrationProcedure type

---

src/convert/transformers/decomposedMetadataTransformer.ts
src/resolve/sourceComponent.ts
test/convert/transformers/decomposedMetadataTransformer.ts

allows you to forceignore children of decomposed metadata types
#<Insert GitHub Issue>, @W-9959024@
adding `**/Account/listViews/**` to your `.forceignore` and then `retrieve -m CustomObject:Account` would retrieve all `ListViews` for `Account`
no `ListViews` or other child metadata types retrieved

fix: run unspecified child types through forceignore to avoid retrieving

---

.mocharc.json
src/registry/nonSupportedTypes.ts
test/registry/registryValidation.test.ts

- removing some nonSupportedTypes that are now avaialable.
- validation to prevent that from happening again
@W-0@

fix: registry validation prevents ignoring non-supported types

---

src/client/metadataTransfer.ts
test/client/metadataTransfer.test.ts

tolerate ETIMEDOUT and ENOTFOUND on all SDR metadata operations
this is just a low-hanging solution for SDR, not jsforce, so we'll have network errors throwing in auth, org create, packaging,  and some other longer-running processes.  But hopefully deploy/retrieve operations (push/pull and the deploy/retrieve/delete and mdapi ops) will be a good partial solve.
partial solve for @W-5657753@
https://github.com/forcedotcom/cli/issues/1301
https://github.com/forcedotcom/cli/issues/529
https://github.com/forcedotcom/cli/issues/1007
SDR throws on first connection problem
```
Error: connect ETIMEDOUT 160.8.252.85:443
at TCPConnectWrap.afterConnect [as oncomplete*** (node:net:1161:16) ***
errno: -110,
code: 'ETIMEDOUT',
syscall: 'connect',
address: '160.8.252.85',
port: 443
***
***
"status": 1, …
```

fix: network error tolerance

---

METADATA_SUPPORT.md
src/i18n/i18n.ts
src/resolve/sourceComponent.ts
test/resolve/sourceComponent.test.ts

when the `fast-xml-parser` library throws an error due to invalid xml, we will parse that error, and add the file that caused the error. 
given a custom labels xml file
```
<?xml version="1.0" encoding="UTF-8"?>
</CustomLabels xmlns="http://soap.sforce.com/2006/04/metadata">
<labels>
<fullName>force_app_Label_1</fullName>
<language>en_US</language>
<protected>true</protected>
<shortDescription>force-app Label 1</shortDescription>
<value>force-app</value>
</labels>
</CustomLabels>
```
note the opening CustomLabels tag is actually a closing tag
#[1261](https://github.com/forcedotcom/cli/issues/1261), @W-10119453@
`TypeError: Cannot read property 'addChild' of undefined`
```
Component conversion failed: error parsing dreamhouse-lwc/force-app/main/default/labels/CustomLabels.labels-meta.xml …
```

fix: wrap error from fast-xml-parser when invalid xml parsed

---

src/client/metadataTransfer.ts
test/client/metadataTransfer.test.ts

adds variable polling frequency to the `pollStatus` method when no value is passed for the frequency
I ended up creating a piece-wise function to capture "small" vs "medium" vs "large" vs "larger" deploys - I'm very open to changing the boundaries and frequencies each should return. I did notice a difference between 250ms and 100ms
@W-9586672@

fix: add variable polling times based on comp. set

---

src/convert/transformers/decomposedMetadataTransformer.ts
src/registry/metadataRegistry.json
src/registry/types.ts
test/convert/transformers/decomposedMetadataTransformer.ts

fixes retrieval of COFT
https://github.com/forcedotcom/cli/issues/1233, https://github.com/forcedotcom/cli/issues/1241, https://github.com/forcedotcom/cli/issues/1262, @W-10222972@
`retrieve -m CustomFieldTranslation` without a CustomObjectTranslation in the org would only pull the CustomFieldTranslation files, which were invalid by themselves without a CustomObjectTranslation parent file
a retrieve will retrieve both COFT/COT and write an empty COT if one doesn't exist in the org

fix: can retrive COFT with COT automatically

---

METADATA_SUPPORT.md
src/client/metadataApiRetrieve.ts
src/client/types.ts
test/client/metadataApiRetrieve.test.ts

Adds support to `MetadataApiRetrieve` for retrieving source in metadata format, naming the zip file that is written, and extracting the zip file contents.
@W-10364895@
no support; only source format
source is retrieved, zip file is written to output directory.  Optionally naming the zip file and extracting the contents to the output dir.

feat: add retrieve in mdapi format

---

contributing/metadata.md

Fixes broken links, typo in the metadata doc

docs: fix broken refs in metadata doc

---

.circleci/config.yml
METADATA_SUPPORT.md

Rather than running all source NUTs in 1 container, break them up so that only some NUTs are run in a container while still running them all.
@W-0@
runs all source nuts in 1 container
runs pieces of source nuts in a container

chore: split source nuts in ci

---

src/collections/componentSet.ts
test/collections/componentSet.test.ts

sort manifest type members and types by name
@W-0@
Functionality Before
output of getPackageXml was not sorted
Functionality After
output of getPackageXml is sorted (type members and types by name)

fix: sort ComponentSet.getObject

---

METADATA_SUPPORT.md
src/client/metadataApiDeploy.ts
test/client/metadataApiDeploy.test.ts

cache getFileResponses inside DeployResult
why?
- plugin-source has to run this in multiple places (source tracking, formatters) and it could be slow for really big deploys
- calling it creates FS operations.  We'd like to only do once
- sometimes we modify the local FS after the retrieve (ex: pull with remote deletes OR source:delete). SDR throws when it can't find files that were in the fileReponses originally
secondary for @W-10666968@

feat: cache fileResponses on deployResult

---

src/registry/metadataRegistry.json

Add new FlowTest type to metadataRegistry
#<[Sfdx force:source for FlowTest](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000Uk6aYAC/view)>, @W-9790379@
Sfdx force:source commands did not work for FlowTest type
Sfdx force:source commands work for FlowTest type

feat(metadata registry): adding flowtest type to metadata registry

---

src/registry/metadataRegistry.json

A previous [PR](https://github.com/forcedotcom/source-deploy-retrieve/pull/580) had added FlowTest to the registry. This PR updates the directoryName for FlowTest.
#<https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000Uk6aYAC/view>, @W-9790379@
FlowTest directoryName was flowTest
FlowTest directoryName is updated to flowtests

fix(metadata registry): update directory name for flowtest in registry

---

HANDBOOK.md
METADATA_SUPPORT.md
contributing/metadata.md
scripts/update-registry/update-supported-metadata.ts

- Fixes broken link to metadata registry file in Handbook
- Updates TOC in Handbook
- AUTO adds `DataImportManagementSettings` to Metadata support doc
@W-10850157@

docs: fix link to metadata registry file; update TOC

---

METADATA_SUPPORT.md
src/resolve/metadataResolver.ts
test/resolve/metadataResolver.test.ts

Fixes `MetadataResolver` to match a file path in source format and mdapi format when testing types with strictDirectoryNames that also do not have an adapter strategy defined (those types are resolved properly another way).
This should fix the following types:
- CustomSite
- IntegrationHubSettings
- AppointmentSchedulingPolicy
- RestrictionRule
- ObjectHierarchyRelationship
- IndustriesManufacturingSettings
- DataSource
- FieldRestrictionRule
- AppointmentAssignmentPolicy
https://github.com/forcedotcom/cli/issues/1448
@W-10910004@
Would not resolve files in mdapi format with certain strictDirectoryName types such as CustomSite.  This would cause (e.g.) a retrieval of these types to fail to be written to the file system.
Files resolve properly.  Metadata retrieval of these files are …

fix: resolve strictDirectoryName types in mdapi format

---

.circleci/config.yml

Use contexts instead of env vars

chore: use salesforce-cli context

---

src/client/metadataApiDeploy.ts

Supports file responses for metadata format deploys that have no component set
@W-10748958@

fix: support file responses for metadata format deploys

---

scripts/update-registry/update2.ts

Fix `scripts/update-registry/update2.ts`, core v3 doesn't export `fs`, replaced with native `fs`.
@W-0@
error `scripts/update-registry/update2.ts:5:10 - error TS2305: Module '"@salesforce/core"' has no exported member 'fs'.` when running `yarn update-registry`
script works

chore: fix registry script

---

src/client/metadataApiDeploy.ts

fixes `archiver` not finalizing larger directories in `MdapiDeploy`
@W-11209280@
` ➜  sfdx force:mdapi:deploy -d src-converted -w 10`
```
➜  ../../oss/plugin-source/bin/run force:mdapi:deploy -d src-converted -w 4
Deploy ID: 0AfJ000002FANRlKAP
*** Deploying with SOAP ***
```

fix: allow larger directories to be compressed, test in plugin-source

---

.circleci/config.yml
package.json
src/registry/coverage.ts
yarn.lock

add proxy support for non-jsforce http requests (using `got` against the coverage report)
note--there's a separate `got` invocation that runs as part of a script, from Circle.  It's not covered by this and works fine without proxy.
This is just for the public part.
@W-11369621@
https://github.com/forcedotcom/cli/issues/1597
the call to the coverage report is triggered when there's no org or project api version to draw from.
use the gh issue repro steps

fix: proxy support for coverage report

---

src/resolve/adapters/mixedContentSourceAdapter.ts
test/resolve/adapters/mixedContentSourceAdapter.test.ts

when forceignore causes *all* of the content in a static resource to be ignored, `tree.exists(undefied)` is called which makes an uglier error.
now it produces a helpful error about which component is causing the problem.
and has a UT for the behavior
@W-11148485@
https://github.com/forcedotcom/cli/issues/1516

fix: static resources without content due to ignore produce nice error

---

METADATA_SUPPORT.md
src/registry/metadataRegistry.json
src/registry/nonSupportedTypes.ts

Adds source tracking for metadata type: IdentityVerificationProcDef
https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000010hdsdYAA/view
@W-11382185@
sfdx force:source commands did not work for IdentityVerificationProcDef metadata entity.
sfdx force:source commands should work for IdentityVerificationProcDef metadata entity.

chore: auto-update metadata coverage in METADATA_SUPPORT.md

---

contributing/metadata.md
src/client/metadataApiDeploy.ts
test/client/metadataApiDeploy.test.ts

remove custom (non `c:`) namespaces from componentFailures in the workaround code 
https://github.com/forcedotcom/cli/issues/1602
@W-11385290@
reported failed LWC deployments as successes if there was a custom namespace.

fix: handle namespaces on lwc markup

---

src/convert/convertContext.ts
test/convert/convertContext.test.ts

Updates `NonDecompositionFinalizer` to only scan the package directories in a DX project when merging non-decomposed metadata.
If the `defaultDirectory` passed to `finalize` isn't a package dir it will ignore it.
See: https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_ws_mpd.htm
https://github.com/forcedotcom/cli/issues/1540
@W-11186731@
`NonDecompositionFinalizer` scans components in root project dir which causes issues when components are found in other folders (mdapi, etc).
`NonDecompositionFinalizer` will only scan components found inside of package directories, if the finalizer gets a defaultDirectory that's not a package it will threat it as the target output dir for a transformation and not scan it.

fix: only scan pkgDirs when merging non-decomposed MD

---

METADATA_SUPPORT.md
src/registry/metadataRegistry.json

**What does this PR do?**
Enable CLI support for ExternalClientApplication
**What issues does this PR fix or reference?**
[@W-11678041@](https://gus.lightning.force.com/a07EE000015NJR0YAO)
**Functionality Before**
sfdx force:source and force:mdapi commands didn't support ExternalClientApplication MD type
**Functionality After**
sfdx force:source and force:mdapi commands support ExternalClientApplication MD type

Enable CLI support for ExternalClientApplication

---

src/registry/nonSupportedTypes.ts
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8370C-CPU-2-80GHz/eda.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8370C-CPU-2-80GHz/lotsOfClasses.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8370C-CPU-2-80GHz/lotsOfClassesOneDir.json

removes `ARCGRAPHCOMMUNITY` feature from blocklist
@W-0@
update-script skips md types with that feature
update-script don't skip them.

chore: don't skip types with `ARCGRAPHCOMMUNITY` feat

---

src/client/metadataApiRetrieve.ts
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8272CL-CPU-2-60GHz/eda.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8272CL-CPU-2-60GHz/lotsOfClasses.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8272CL-CPU-2-60GHz/lotsOfClassesOneDir.json

customFieldTranslations weren't showing up in FileResponses for retrieve.  the corrected logic from Deploy is now in Retrieve.
kinda a followup for https://github.com/forcedotcom/source-deploy-retrieve/pull/726
so @W-11811429@

fix: show individual cft in a retrieve

---

METADATA_SUPPORT.md
src/registry/metadataRegistry.json

Update sfdx to support RelationshipGraphDefinition
[W-11471632] Missing metadata type definition in registry for id 'relationshipgraphdefinition'
https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE0000120bcLYAQ/view
When retrieving graph definition via Visual Studio sfdx extension they get this error
> Error - Missing metadata type definition in registry for id 'relationshipgraphdefinition'

chore: support RelationshipGraphDefinition

---

.github/workflows/perfScaleNut.yml
.github/workflows/registryCheck.yml
.github/workflows/registryCheckPreview.yml
src/resolve/manifestResolver.ts
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8272CL-CPU-2-60GHz/eda.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8272CL-CPU-2-60GHz/lotsOfClasses.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8272CL-CPU-2-60GHz/lotsOfClassesOneDir.json
test/resolve/manifestResolver.test.ts

throw an error during manifest parsing when a metadata type appears invalid, indicating a bad manifest file.
@W-11927256@
"Cannot read property 'toLowerCase' of undefined"
https://github.com/forcedotcom/cli/issues/1187
Invalid types definition in manifest file: package.xml
Found: ""
Testing:
Create a manifest file with an empty `<types></types>` definition inside and run `sfdx force:source:retrieve -x package.xml`

fix: add a better error message with invalid manifests

---

METADATA_SUPPORT.md
src/registry/metadataRegistry.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8272CL-CPU-2-60GHz/eda.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8272CL-CPU-2-60GHz/lotsOfClasses.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8272CL-CPU-2-60GHz/lotsOfClassesOneDir.json

Enable CLI support for ExtlClntAppOauthPlcyCnfg, ExtlClntAppOauthSettings, ExtlClntAppMobileSet 
#[W-11950652](https://gus.lightning.force.com/a07EE000019d9dwYAA)
sfdx force:source and force:mdapi commands didn't support MD type for ExtlClntAppOauthPlcyCnfg, ExtlClntAppOauthSettings, ExtlClntAppMobileSet 
sfdx force:source and force:mdapi commands supports MD type for ExtlClntAppOauthPlcyCnfg, ExtlClntAppOauthSettings, ExtlClntAppMobileSet

Enable CLI support for ExtlClntAppOauthPlcyCnfg, ExtlClntAppOauthSettings, ExtlClntAppMobileSet 

---

METADATA_SUPPORT.md
src/client/metadataApiDeploy.ts
src/client/types.ts
src/convert/replacements.ts
src/convert/types.ts
test/convert/replacements.test.ts
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8272CL-CPU-2-60GHz/eda.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8272CL-CPU-2-60GHz/lotsOfClasses.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8272CL-CPU-2-60GHz/lotsOfClassesOneDir.json

when replacements happen in the replacement stream, emit events
aggregate those up to the metadataApiDeploy class and, when done, set them on the DeployResult so that library consumers can know what occurred.
@W-11949818@

feat: replacements in output

---

METADATA_SUPPORT.md
src/registry/metadataRegistry.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8272CL-CPU-2-60GHz/eda.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8272CL-CPU-2-60GHz/lotsOfClasses.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8272CL-CPU-2-60GHz/lotsOfClassesOneDir.json

Enable CLI support for ExtlClntAppOauthConfigurationPolicies, ExtlClntAppMobileSettings. MD names are refactored from ExtlClntAppOauthPlcyCnfg and ExtlClntAppMobileSet respectively.
[W-11950652](https://gus.lightning.force.com/a07EE000019d9dwYAA)
sfdx force:source and force:mdapi commands didn't support MD type for ExtlClntAppOauthConfigurationPolicies, ExtlClntAppMobileSettings
sfdx force:source and force:mdapi commands supports MD type for ExtlClntAppOauthConfigurationPolicies, ExtlClntAppMobileSettings

Enable CLI support for ExtlClntAppOauthConfigurablePolicies, ExtlClntAppMobileSettings

---

contributing/metadata.md
src/registry/metadataRegistry.json
src/registry/types.ts
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8272CL-CPU-2-60GHz/eda.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8272CL-CPU-2-60GHz/lotsOfClasses.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8272CL-CPU-2-60GHz/lotsOfClassesOneDir.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8370C-CPU-2-80GHz/eda.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8370C-CPU-2-80GHz/lotsOfClasses.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8370C-CPU-2-80GHz/lotsOfClassesOneDir.json

Adds a `supportsPartialDelete` property to registry entries to denote that a metadata type should do a deploy when only part of the files that make up the metadata are deleted, rather than a delete.
@W-11385865@
@W-11828599@

fix: add supportsPartialDelete property to registry

---

src/convert/metadataConverter.ts
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8272CL-CPU-2-60GHz/eda.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8272CL-CPU-2-60GHz/lotsOfClasses.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8272CL-CPU-2-60GHz/lotsOfClassesOneDir.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8370C-CPU-2-80GHz/eda.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8370C-CPU-2-80GHz/lotsOfClasses.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8370C-CPU-2-80GHz/lotsOfClassesOneDir.json

Adds the error message to the new error when the caught error is a String.
https://github.com/forcedotcom/cli/issues/1420
@W-12099973@
```
sfdx force:source:deploy -p force-app/main/default/classes/PagedResult.cls
*** Deploying with SOAP API v56.0 ***
ERROR running force:source:deploy:  Component conversion failed: undefined
```
```
sfdx force:source:deploy -p force-app/main/default/classes/PagedResult.cls
*** Deploying with SOAP API v56.0 ***
ERROR running force:source:deploy:  Component conversion failed: error converting stream - Error: ENOENT: no such file or directory, open '.../ebikes-lwc/force-app/main/default/classes/PagedResult.cls-meta.xml'
```

fix: include string errors during convert

---

METADATA_SUPPORT.md
package.json
src/client/metadataApiDeploy.ts
src/client/metadataApiRetrieve.ts
src/collections/componentSet.ts
src/collections/componentSetBuilder.ts
test/client/metadataApiRetrieve.test.ts
test/collections/componentSet.test.ts
test/nuts/perfResults/x64-linux-2xIntel-Xeon-CPU-E5-2673-v4-2-30GHz/eda.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-CPU-E5-2673-v4-2-30GHz/lotsOfClasses.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-CPU-E5-2673-v4-2-30GHz/lotsOfClassesOneDir.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8272CL-CPU-2-60GHz/eda.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8272CL-CPU-2-60GHz/lotsOfClasses.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8272CL-CPU-2-60GHz/lotsOfClassesOneDir.json
yarn.lock

Corrects the code that determines the apiVersion and sourceApiVersion before sending a deploy or retrieve.  Also emits an event with this data just before sending so that consumers can act upon it (e.g., display useful output).
The proper priority for determining the API version of the connection (items higher on the list take precedence) is:
1. `apiversion` command flag
2. `SFDX_API_VERSION` env var
3. local config var
4. global config var
5. highest version supported by the target org
The proper priority for determining the manifest version (items higher on the list take precedence) is:
1. `<version>` in package.xml 
2. `sourceApiVersion` in sfdx-project.json
3. `apiversion` command flag
4. `SFDX_API_VERSION` env var
5. local config var
6. global config var
7. highest version supported …

fix: correct apiVersion and sourceApiVersion values before transfer and send events

---

METADATA_SUPPORT.md
src/registry/metadataRegistry.json
src/registry/nonSupportedTypes.ts

Enable CLI support for FuelType, FuelTypeSustnUom, SustainabilityUom and SustnUomConversion setup entities
@[W-11973061](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001A9o6FYAR/view)@
sfdx force:source and force:mdapi commands didn't support FuelType, FuelTypeSustnUom, SustainabilityUom, and SustnUomConversion MD types
sfdx force:source and force:mdapi commands support FuelType, FuelTypeSustnUom, SustainabilityUom and SustnUomConversion MD types

Enable CLI support for FuelType, FuelTypeSustnUom, SustainabilityUom, SustnUomConversion

---

src/resolve/connectionResolver.ts
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8370C-CPU-2-80GHz/eda.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8370C-CPU-2-80GHz/lotsOfClasses.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8370C-CPU-2-80GHz/lotsOfClassesOneDir.json

fixes creating a manifest with StandardValueSets
[#<Insert GitHub Issue>](https://github.com/forcedotcom/cli/issues/1877), @W-12402176@
`source:manifest:generate --fromorg` wouldn't add `StandardValueSet` metadata to the manifest
`STandardValueSet` metadata is in the manifest

fix: await SVS promises to write to manifest

---

src/client/metadataTransfer.ts
test/nuts/perfResults/x64-linux-2xIntel-Xeon-CPU-E5-2673-v4-2-30GHz/eda.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-CPU-E5-2673-v4-2-30GHz/lotsOfClasses.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-CPU-E5-2673-v4-2-30GHz/lotsOfClassesOneDir.json

only emits the "beyond max api version" event once to prevent 
```
➜  sfdx force:source:deploy -p force-app --apiversion=57.0 
(node:71680) Warning: The requested API version (57.0) is higher than the org supports.  Using 56.0.
(Use `node --trace-warnings ...` to show where the warning was created)
Deploying v55.0 metadata to test-y2wsfd5m2no3@example.com using the v56.0 SOAP API
Deploy ID: 0Af8G00000UQfwNSAT
(node:71680) Warning: The requested API version (57.0) is higher than the org supports.  Using 56.0.
(node:71680) Warning: The requested API version (57.0) is higher than the org supports.  Using 56.0.
DEPLOY PROGRESS | ███░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ | 6/89 Components(node:71680) Warning: The requested API version (57.0) is higher than the org supports.  Using 56.0. …
```

fix: only emit events once per lifecycle

---

METADATA_SUPPORT.md
src/registry/metadataRegistry.json
src/registry/nonSupportedTypes.ts

Updates the metadata registry by running `yarn update-registry` against a gs0 devhub and the metadata coverage by running `yarn update-supported-metadata`.
N/A

feat: update metadata support and auto-update metadata coverage

---

src/client/metadataApiRetrieve.ts
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8370C-CPU-2-80GHz/eda.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8370C-CPU-2-80GHz/lotsOfClasses.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8370C-CPU-2-80GHz/lotsOfClassesOneDir.json

when handling partial bundle delete retrieves, ignore any forceignored files/directories.  E.g., the `__tests__` dir of an LWC
#1904
@W-12460543@

fix: handle forceignored files for partial bundle deletes

---

src/registry/metadataRegistry.json
src/resolve/metadataResolver.ts
src/utils/filePathGenerator.ts
test/nuts/scale/eda.nut.ts
test/nuts/scale/lotsOfClasses.nut.ts
test/nuts/scale/lotsOfClassesOneDir.nut.ts

With this PR we are adding a new metadata bundle ExperiencePropertyType. This bundle is very similar to waveTemplates. We dont have *meta.xml file, the bundles entirely contains JSON files.
With this PR we are adding a new metadata bundle ExperiencePropertyType. [W-12502730]
Before this change sfdx source-tracking/packaging doesn't support ExperiencePropertyType bundle.
After this change sfdx source-tracking/packaging will support ExperiencePropertyType bundle.

feat(adding experiencepropertytype bundle): support for ExperiencePropertyType Bundle

---

src/client/metadataApiRetrieve.ts
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8272CL-CPU-2-60GHz/eda.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8272CL-CPU-2-60GHz/lotsOfClasses.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8272CL-CPU-2-60GHz/lotsOfClassesOneDir.json

When retrieving bundle type metadata that has some pieces of the bundle deleted (or it looks that way because there are more local files than what was retrieved), only delete the pieces that are not forceignored.
@W-12460543@
https://github.com/forcedotcom/cli/issues/1904
would delete the entire component and replace with what was retrieved if there was any file within the component locally that was not retrieved, even if forceignored.
Removes pieces of a component only if they are not forceignored and they were not part of the retrieve.

fix: only delete non-forceignored sub-directories

---

HANDBOOK.md

The code blocks in the docs were missing the typescript tags that enables syntax highliting when rendering in GitHub
Couldn't create issue for this 
No Syntax highlighting when viewing code blocks in browser
Syntax highlighting when viewing code blocks in browser

docs: update handbook doc with typescript tag in code blocks

---

.github/workflows/failureNotifications.yml
.github/workflows/supportedMetadataUpdate.yml
.husky/pre-push
contributing/metadata.md
scripts/update-registry/update-supported-metadata.ts
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8370C-CPU-2-80GHz/eda.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8370C-CPU-2-80GHz/lotsOfClasses.json
test/nuts/perfResults/x64-linux-2xIntel-Xeon-Platinum-8370C-CPU-2-80GHz/lotsOfClassesOneDir.json

updating of  https://github.com/forcedotcom/source-deploy-retrieve/blob/main/METADATA_SUPPORT.md will happen from a daily gha job instead of a commit hook.

ci: metadata support updates as a scheduled job

---

src/registry/nonSupportedTypes.ts

tried to add 2 types to the registry.  Using their scratch-def from the MetadataCoverageReport, they do not appear in the describe.
So I added them to the nonSupportedTypes instead
https://github.com/forcedotcom/source-deploy-retrieve/actions/runs/4591081684
[skip-pr-validate]

chore: exclude new types with incorrect scratch settings

---

src/resolve/adapters/digitalExperienceSourceAdapter.ts
test/resolve/adapters/digitalExperienceSourceAdapter.test.ts

Updates method for trimming a path up until the root of a component's content to handle screen aware variants
Ensures Retrieval and deployment of a view with screen aware variants is working via sfdx commands
@W-12171473@
DEB adapters in SFDX project are not handling mobile and tablet variant files in the content folders but only the _meta.json and content.json file. Hence, we are getting errors when we have mobile or tablet variants in the bundle.
DEB adapters will be to handle the screen variant case as method trimPathToContent() is updated to give correct directory hierarchy for screen variants .Eg- digitalExperiences/site/lwr11/sfdc_cms__view/home/mobile/mobile.json

fix: ensure retrieval and deployment of views with screen aware variants

---

src/convert/metadataConverter.ts
src/convert/transformers/staticResourceMetadataTransformer.ts
test/convert/metadataConverter.test.ts

> requires https://github.com/salesforcecli/plugin-source/pull/801 (ps-nuts change)
the SDR strict changes had already "fixed" the bug so that it gives an error, but there was room for improvement.
Also added some logic so that "good errors" thrown from deep in the convert process don't get genericized (losing their name and actions) by metadataConverter.
https://github.com/forcedotcom/cli/issues/1384
```
Error (1): Component conversion failed: FILE_ENDED
```

fix: better error messages around static resource converstion failures

---

src/resolve/connectionResolver.ts

Make SDR retry on network errors like ETIMEDOUT when querying info about metadata types.
@W-13056201@
`force source manifest create` would exit successfully with an incomplete manifest because SDR ignores errors when getting MD info.
`SDR` retries on network errors, if polling client times out then throw error (sfdx should catch the error and fail).

fix: retry on net errors when retrieving MD info

---

src/registry/metadataRegistry.json

Update directory name for oauth policies and mobile policies
[W-13098569](https://gus.lightning.force.com/a07EE00001QAU2gYAH)
ExtlClntAppOauthConfigurablePolicies had directory name oauthPolicies. 
ExtlClntAppMobileConfigurablePolicies had directory name mobilePolicies. 
ExtlClntAppOauthConfigurablePolicies now has directory name extlClntAppOauthPolicies. 
ExtlClntAppMobileConfigurablePolicies now has directory name extlClntAppMobilePolicies.

fix: update directory name for oauth policies and mobile policies

---

scripts/update-registry/update2.ts
tsconfig.json

Updates the update2.ts script for TS strict compilation and adds the scripts/update-registry folder to tsconfig.json so it's compiled during `yarn compile`
@W-13137391@
You get TS compile errors when running `yarn update-registry`
Script runs as expected; no compile errors.

fix: update the update2 script for TS strict compile

---

.github/workflows/test.yml
package.json
src/convert/replacements.ts
test/convert/replacements.test.ts
yarn.lock

smarter matching of file paths for replacements on windows
https://github.com/forcedotcom/cli/issues/1885 
@W-12398244@
[Metadata string replacements](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_ws_string_replace.htm) were working inconsistently on windows depending on what shell you used.   Special thanks to [micha79x](https://github.com/micha79x) for a love repro/repo and doing most of the detective work on this one.

fix: windows path replacements

---

METADATA_SUPPORT.md
src/registry/metadataRegistry.json

Adds new MetadataType 'SkillType' to the registry.
@W-13175866@
SkillType metadata type is not accessible through SFDX cli
SkillType metadata type is accessible through SFDX cli

Adding skilltype to metadata registry

---

package.json
src/client/diagnosticUtil.ts
test/client/diagnosticUtil.test.ts
yarn.lock

This is a follow-on from strict mode update where we get better error messages.  Call JSON.stringy instead of toString() to get better output.
Also adds the the component name information and consolidates some error message generation.
@W-13222350@ https://github.com/forcedotcom/cli/issues/2140

fix: prevent [object Object] and provide component details

---

METADATA_SUPPORT.md
src/registry/metadataRegistry.json

Adds new MetadataType 'ScoreCategory' to the registry.
@W-13311344@
ScoreCategory metadata type is not accessible through SFDX cli
ScoreCategory metadata type is accessible through SFDX cli

@W-13311344 Adding ScoreCategory to metadata registry

---

messages/sdr.md

Add messaging about checking registry, coverage report, and contributing mdTypes.
@W-12488887@

feat: missing type language

---

src/resolve/manifestResolver.ts
test/resolve/manifestResolver.test.ts

validate manifests are valid xml
@W-13505922@
`successfully wrote package.xml` (but ignored invalid types)
```bash
Error (1): Invalid manifest file: package.xml.
InvalidTag Tag '<types' is an invalid name. (Line 3 Column 12)
```

feat: validate manifests

---

package.json
src/registry/coverage.ts
yarn.lock

Bumps major version of `proxy-agent`, which also means we can delete the `proxy-from-env` dependency too since `proxy-agent` uses it under the covers.
Also bump `fast-xml-parser` minor versions.
@W-13546885@

fix: bump versions of fast-xml-parser and proxy-agent

---

src/resolve/connectionResolver.ts

better error message 
https://github.com/forcedotcom/cli/issues/2229
@W-13623848@

fix: better output for mystery component

---

METADATA_SUPPORT.md
src/registry/metadataRegistry.json

update metadata names for mobile settings and policies
[W-13519963](https://gus.lightning.force.com/a07EE00001SkRSAYA3)
Metadata name for mobile settings was ExtlClntAppMobileSettings.
Metadata name for mobile policies was ExtlClntAppMobileConfigurablePolicies.
Metadata name for mobile settings is now ExtlClntAppSampleSettings.
Metadata name for mobile policies is now ExtlClntAppSampleConfigurablePolicies.

fix: update metadata names for mobile settings and policies

---

messages/sdr.md
src/resolve/adapters/matchingContentSourceAdapter.ts
test/resolve/adapters/matchingContentSourceAdapter.test.ts

we weren't showing the actions correctly for an error
https://github.com/forcedotcom/cli/issues/2237
@W-13628477@

fix: restore missing error actions

---

src/registry/metadataRegistry.json

Add metadata types for mobile settings and policies
[@W-13681494@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001V4RYlYAN/view)
N/A
Metadata name for mobile settings was ExtlClntAppMobileSettings.
Metadata name for mobile policies was ExtlClntAppMobileConfigurablePolicies.

fix: add mobile plugin types to registry

---

src/registry/stdValueSetRegistry.json

Looks like there's a 2nd standard valueset that's nearly identical and we need both
follow-on to https://github.com/forcedotcom/source-deploy-retrieve/pull/1031
see also https://salesforce-internal.slack.com/archives/C01LKDT1P6J/p1690202194657049
https://github.com/forcedotcom/cli/issues/2163

fix: missing stdValue

---

src/client/metadataApiDeploy.ts
src/client/metadataApiRetrieve.ts
src/resolve/metadataResolver.ts
src/resolve/sourceComponent.ts
test/client/metadataApiDeploy.test.ts

found a bug where a really large mdapi retrieve (4000+ components) would cause `Maximum call stack size exceeded`
it's coming from mutating array (via push) of a spread of a really large array.  Each item in the the array is an entire SourceComponent and we know how massive that object is since each one contains the whole registry, etc.
This solution converts the one causing the bug and a few other potentially dangerous `x.push(...maybeLargeArray)` to `concat`/reassign, which can accept multiple arrays to concat, but then each one is only a 1 pointer to an array instead of thousands of items.  Seems to work.
https://javascript.plainenglish.io/deal-with-maximum-call-stack-size-exceeded-error-in-javascript-45c035161a78
This solved that problem 
@W-13783924@
QA: the referenced WI contains …

fix: spread/push argument limits

---

src/convert/transformers/decomposedMetadataTransformer.ts
test/convert/transformers/decomposedMetadataTransformer.test.ts

top-level Decomposed types could be retrieved with *
@W-13813099@
put `Broker__c` in your forceignore like `**/objects/Broker__c`
delete `objects/Broker__c` folder from local project
`sf project retrieve start --metadata CustomObject`  (this will cause `*` for CustomObject)
you see broker retrieved without this PR.

fix: ignored, decomposed parent

---

src/collections/componentSetBuilder.ts
test/collections/componentSetBuilder.test.ts

allows you to pass a wildcard as part of a full name when construction a component set via metadata
e.g.
`'FlexiPage:Property*' `
https://github.com/forcedotcom/cli/issues/2386 @W-13867893@
would error
Deploys FlexiPages that match `Property*`
Retrieves as well*
*when the metadata already exists locally
```bash
force:source:deploy -m 'FlexiPage:Property*' 
...
DEPLOY PROGRESS | ████████████████████████████████████████ | 3/3 Components
=== Deployed Source
FULL NAME            TYPE      PROJECT PATH                                                              
──────────────────── ───────── ───────────────────────────────────────────────────────────────────────── 
Property_Explorer    FlexiPage force-app/main/default/flexipages/Property_Explorer.flexipage-meta.xml    
Property_Finder …
```

feat: add a wildcard expansion to metadata full names when building the CS

---

src/resolve/treeContainers.ts
test/resolve/treeContainers.test.ts

SDR would exit streams early on ENOENT without throwing an error
this checks file existence before doing a readStream from the file
[this would be more efficient, on the happy path, to catch this error but it seems to buried inside nested streams and this is a simple fix.  It *would* error much earlier in the convert process if the error is going to happen.  Perf benchmarks suggest it has a negative impact]
https://github.com/forcedotcom/cli/issues/2011
@W-12769219@

fix: throw when expected file is ENOENT

---

src/collections/componentSet.ts
src/collections/decodeableMap.ts
test/collections/decodeableMap.test.ts

Creates a new DecodeableMap class that extends the standard Map.  A DecodableMap is the same as a Map except that the key must be a string, and whenever passing a key it will match on the exact text and the decoded text.  Since `ComponentSet.components` Maps use component fullNames as keys, this allows encoded fullNames to match decoded fullNames, and vice versa.
@W-11658886@

feat!: component set components are now DecodableMaps

---

src/registry/metadataRegistry.json

Add FundraisingConfig to Metadata Registry.
unable to access FundraisingConfig metadata from CLI
able to access FundraisingConfig metadata from CLI

fix: @W-12612279 Adding FundraisingConfig to metadata registry

---

src/registry/coverage.ts

decommissioning of R&D instance moved these coverage report urls
original issue: https://salesforce-internal.slack.com/archives/C01LKDT1P6J/p1695757070779679
new stuff: https://salesforce-internal.slack.com/archives/C01Q2LR8NQM/p1695760962073649

fix: new coverage locations

---

METADATA_SUPPORT.md
src/registry/metadataRegistry.json

Add ConversationChannelDefinition as supported metadata CLI type for v59.0
User cannot do metadata retrieve command with ConversationChannelDefinition in the org
User can do metadata retrieve command with ConversationChannelDefinition in the org

fix: update ConversationChannelDefinition as supported MD CLI for v59.0

---

src/convert/streams.ts
test/convert/streams.test.ts

- manual string.replaceAll for the htmlEntity in this issue, with convenient expansion in the future.
- see comment about the other options that I found out won't work 
https://github.com/forcedotcom/cli/issues/2448
@W-14079220@
QA: see comment on issue about what happens when you run retrieve on these (it's never worked, and still doesnt).
The value retrieved from the org turns into a space even when retrieving in mdapi format, so there's nothing we an do about that but raise a bug for the Labels team

fix: one-off handling of 1 html entity

---

src/registry/metadataRegistry.json

Adds support for [EventRelayConfig Metadata Type](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_eventrelayconfig.htm) to Metadata Registry 
On running `sfdx force:mdapi:retrieve` or `sfdx force:mdapi:deploy` with EventRelayConfig as a part of pacakge.xml the observed behavior is 
`ERROR running force:mdapi:retrieve: The specified metadata type is unsupported: [eventrelayconfig]
`
SFDX retrieve and SFDX deploy commands with EventRelayConfig work.

fix: metadata type support for EventRelayConfig

---

src/client/metadataApiDeploy.ts
test/client/metadataApiDeploy.test.ts

put col/line in mdapi results for component failures.
Will be consumed by PDR in separate PR
https://github.com/forcedotcom/cli/issues/356
@W-14247072@

test: ut for mdapi line/col numbers

---

src/client/metadataApiDeploy.ts
test/client/metadataApiDeploy.test.ts

removes duplicates from file responses
before:
```bash
➜  bug sf project deploy start --metadata-dir dup
Debugger listening on ws://127.0.0.1:9229/b0f755b5-6e94-4861-8126-144a41f751ba
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Deploying <version specified in manifest> metadata to test-bavzogrje67w@example.com using the v58.0 SOAP API.
Deploy ID: 0Af8N00000uI9ZCSA0
Status: Failed | ████████████████████████████████████████ | 2/2 Components (Errors:2) | 0/0 Tests (Errors:0)
Debugger ending on ws://127.0.0.1:9229/b0f755b5-6e94-4861-8126-144a41f751ba
For help, see: https://nodejs.org/en/docs/inspector
Component Failures [2]
===============================================================
| Type  Name             Problem                    Line:Column 
| ───── …
```

fix: remove duplicates from file responses

---

src/convert/streams.ts
src/convert/transformers/decomposedMetadataTransformer.ts
src/resolve/adapters/decomposedSourceAdapter.ts
test/convert/transformers/decomposedMetadataTransformer.test.ts
yarn.lock

allows `CustomFieldTranslation` MDT to be retrieved across MPDs
https://github.com/forcedotcom/cli/issues/2124 @W-13193003@
with a remote change to a CFT, the parent COT being in the non-default package dir, and running a `force source pull`
```bash
➜  pull
Preparing retrieve request... ⣾
Preparing retrieve request... MetadataTransferError
Error (1): Metadata API request failed: Unexpected child metadata [/Users/william.ruemmele/projects/scratches/sfdx-translation-bug/package-a-app/main/default/objectTranslations/customObject__c-es/customField__c.fieldTranslation-meta.xml] found for parent type [CustomObjectTranslation]
```
```bash
➜  sf force source pull                                
Warning: We plan to deprecate this command in the future. Try using the "project retrieve start" …
```

fix: Wr/coft mpd

---

src/registry/metadataRegistry.json

Adde support to managedEventSubscription metadata to SF CLI
#@W-14358125@

fix: support metadata type managedEventSubscription

---

src/collections/decodeableMap.ts
test/collections/decodeableMap.test.ts

Any errors thrown while looking for decoded keys are handled.  Adds a unit test.
@W-14457431@
https://github.com/forcedotcom/cli/issues/2560

fix: catch decoding errors

---

src/client/types.ts
src/collections/componentSet.ts
src/convert/replacements.ts
src/convert/streams.ts
src/convert/transformers/staticResourceMetadataTransformer.ts
src/resolve/adapters/baseSourceAdapter.ts
src/resolve/manifestResolver.ts
src/resolve/metadataResolver.ts
src/resolve/sourceComponent.ts
src/utils/filePathGenerator.ts
test/mock/client/transferOperations.ts
test/resolve/connectionResolver.test.ts

cleans up some things the linter didn't like.  Most of them are related to using truthiness on things that can be undefined in stuff chained by `||`.  A few were actual problems...the others are a bit much.  The logic was fine, but harder for the linter to know, with non-booleans, whether the `||` was being used a logical OR vs. fallback if falsy.
kinda fallout from [@W-14373783@](https://gus.lightning.force.com/a07EE00001dDMpBYAW)
https://github.com/forcedotcom/eslint-config-salesforce-typescript/actions/runs/6720828841/job/18265239393

fix(lint): current linter rules

---

src/collections/componentSet.ts
src/collections/componentSetBuilder.ts
src/collections/types.ts
src/resolve/connectionResolver.ts
test/collections/componentSetBuilder.test.ts
test/resolve/connectionResolver.test.ts

Enhances `ComponentSetBuilder.build()` to use both metadata and an org connection when defined in the options.  This allows metadata fullName retrieval from an org based on a pattern where the files are not in the local project.
@W-14284096@
https://github.com/forcedotcom/cli/issues/2522
QA suggestions:
Use dreamhouse-lwc repo deployed to a scratch org.
1. deploy should work exactly as before the changes were made.  Deploy `"ApexClass:Test*"`, `"ApexClass:T*"`, `"ApexClass:Test*,ApexClass:Geo*"`, `"ApexClass:Test*,CustomObject:Prop*"`
2. retrieve with all requested files in the project.  Retrieve `"ApexClass:Test*"`, `"ApexClass:T*"`, `"ApexClass:Test*,ApexClass:Geo*"`, `"ApexClass:Test*,CustomObject:Prop*"`
3. retrieve with none of the requested files in the project.  Retrieve …

feat: build ComponentSet using metadata and an org connection

---

package.json

missing dep for ts-retry-promise

fix: implicit dependency

---

messages/sdr.md
src/collections/componentSet.ts
src/registry/coverage.ts
test/collections/componentSet.test.ts

Changes the URL to get an API version from https://mdcoverage.secure.force.com/services/apexrest/report to https://dx-extended-coverage.my.salesforce-sites.com/services/data
If neither `sourceApiVersion` nor `apiVersion` were set on a `ComponentSet` before calling `getObject()`, will then look for and use (in order):
1. sourceApiVersion set in sfdx-project.json
2. apiVersion from ConfigAggregator (config files and Env Vars)
3. http call to /services/data endpoint for highest apiVersion
4. hardcoded value of "58.0" as a last resort
@W-14621701@

fix: change mdcoverage url for getCurrentApiVersion

---

METADATA_SUPPORT.md
src/registry/metadataRegistry.json

Adds new MetadataTypes 'ExtDataTranObjectTemplate' and 'ExtDataTranFieldTemplate' to the registry.
@W-14674743@
Functionality Before
force:mdapi:deploy didn't work for 'ExtDataTranObjectTemplate' and 'ExtDataTranFieldTemplate' meta data types
Functionality After
force:mdapi:deploy works for 'ExtDataTranObjectTemplate' and 'ExtDataTranFieldTemplate' meta data types

fix: Qa/1202 - add support for ExtDataTranObjectTemplate and ExtDataTranFieldTemplate

---

src/registry/metadataRegistry.json

adds DataCalcInsightTemplate and DataKitObjectTemplate metadata types to the registry

fix: add DataCalcInsightTemplate and DataKitObjectTemplate

---

src/registry/metadataRegistry.json

Adds ExtlClntAppNotificationSettings type to the registry.
[@W-14035929@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001ZcRR3YAN/view)
N/A
ExtlClntAppNotificationSettings metadata type is exposed in registry.

fix: add ExtlClntAppNotificationSettings to registry

---

src/registry/metadataRegistry.json

Fixed metadataRegistry entries for IdentityVerificationProcDev.  The casing was wrong.
I tested this with an org that had a few of this type and was able to retrieve them with this change.

fix: metadataRegistry entries for IdentityVerificationProcDev were incorrect

---

src/registry/coverage.ts

When an API version is needed yet not provided in other ways to the SDR APIs, make a call to the appexchange org to get the most recent API version.  Also, save the result so that all other calls to `getCurrentApiVersion()` on the same process use that value rather than making another call to that endpoint.
@W-14848514@

fix: use appexchange org for last resort api version

---

src/registry/metadataRegistry.json

Adding support for GenAiPromptTemplates
adding these metadata types:
genaiprompttemplate and genaiprompttemplateactv
#<https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001ivtJDYAY/view>, @W-14902095@

@W-14902095 feat: adding gen ai prompt template support

---

src/resolve/forceIgnore.ts
test/resolve/forceIgnore.test.ts

SDR's was loading its defaults AFTER the user's `.forceignore` contents.  This change switches the order so that users can override the defaults (in this case, NOT ignoring `**/.*`) 
@W-14892481@
https://github.com/forcedotcom/cli/issues/2666
by default, files starting with dots are ignored because of `DEFAULT_IGNORE`. 
With this change, you can add `!**/.*` to your `.forceignore` and it'll override the defaults.

fix: override forceignore defaults

---

src/registry/metadataRegistry.json

Expose new EnablementMeasureDefinition Metadata type to CLI / 2GP Packaging / Unlocked Packaging
@W-14972256@
https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001jVpAZYA0/view
EnablementMeasureDefinition not usable in CLI or 2nd gen packaging
EnablementMeasureDefinition usable in CLI and 2nd gen packaging

@W-14972256@ Expose EnablementMeasureDefinition to CLI

---

src/convert/transformers/decomposedMetadataTransformer.ts

pulling forward changes from https://github.com/forcedotcom/source-deploy-retrieve/pull/1217/commits/06afe57a22cb999e1c0a1fa196d919354a2626aa  and https://github.com/forcedotcom/source-deploy-retrieve/pull/1217/commits/e43d6f4f130859d0b5dbbc851c197dfb46b7eee2
(part of larger registryCustomizations work)
needed for 
[@W-14335636@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001coha6YAA/view)
[@W-13478725@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001SB1tCYAT/view)
https://github.com/forcedotcom/source-deploy-retrieve/pull/1231
only fullname is used for the uniqueIdElement
decomposed by folders only use directoryNames
`uniqueIdElement` specified in the registry is used.  fullname and name are still the fallbacks when that isn't present …

fix: decompose by any folder name

---

src/registry/metadataRegistry.json

Fixed the incorrect case for the new EnablementMeasureDefinition metadata type name.
@W-14972256@
`Entity type: 'Enablementmeasuredefinition' is unknown` when using `sf project retrieve start`
Entity is retrieved correctly

@W-14972256@ Fix incorrect case for EnablementMeasureDefinition metadata type name

---

src/convert/convertContext.ts

recomposition of decomposed objects uses the directory name as the xml element.
This was fine for CustomObject.field because `/fields` is the child directoryName AND happens to be XML element `<fields>`
Use the registry's xmlElementName if provided, default to the directoryName otherwise.
needed to make these work, though there are bigger mdapi issues there.
@W-14335636@
@W-13478725@

fix: recompose decomposed xml using xmlElementName where it exists

---

src/resolve/treeContainers.ts

handles `undefined` being passsed to a method that expects strings.  It'd be *better* if all the consumers of this warned which component was missing its filename in the MDAPI reponse, but this at least prevents the unhelpful error.
How'd this get by us?  The mdapi response isn't matching its expected typing.  I'm guessing that's a server bug related to the new release, but am waiting for the full `deployResult` so I can inspect its contents.  One of the [DeployMessage](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_deployresult.htm#deploymessage) is unexpectedly missing the `fileName` property.  
ex: https://github.com/forcedotcom/cli/issues/2697
also got a report of this happening on `push`
```{
"code": 10.0,
"context": "Push",
"commandName": "Push", …
```

fix: defend against bad mdapi responses

---

src/registry/metadataRegistry.json

We have created a new setup entity EnablementProgramDefinition and exposed it to mdApi.
Supports EnablementProgramDefinition entity in retrieve/deploy
The specified metadata type is unsupported: [enablementprogramdefinition]
@W-14771527@
When we tried to retrieve this entity using sfdx commands getting the following error The specified metadata type is unsupported: [enablementprogramdefinition]

 @W-14771527: Changes to support EnablementProgramDefiniton

---

src/convert/replacements.ts
test/nuts/local/replacements/replacementsLabels.nut.ts

When individual `CustomLabel` metadata with string replacements are targeted for a deploy without the parent `CustomLabels` metadata, the string replacement won't occur due to the code using cached file content.  This PR sets replacements on a parent component when the child has string replacements.
[CustomLabel String replacement not working correctly with --manifest flag](https://github.com/forcedotcom/cli/issues/2755)
@W-15262083@

fix: handle string replacements for individual custom labels

---

src/client/metadataTransfer.ts

Adds 502, 503, and 420 error codes to list of responses to retry during deploy polling.
@W-15289218@

fix: refactor for better typing and readability

---

src/convert/metadataConverter.ts

restore a unspecified type behavior that packaging was relying on

fix: non-zip conversions return empty arrays for converted and deleted

---

src/registry/metadataRegistry.json

It registers AffinityScoreDefinition as a metadata type so that we can make AffinityScoreDefinition entity packageable.

@W-15215917: feat: add AffinityScoreDefinition metadatatype

---

src/registry/variants.ts
test/nuts/scale/perfUtils.ts

1. add telemetry for registry variants
2. cleanup a longstanding todo
@W-15380923@

feat: variants instrumentation

---

src/client/metadataTransfer.ts

updates `MetadataTransfer.pollStatus` error handling to expand the mdTransfer error with error data/actions if the failure throws an SfError.
An example of this is STL throwing on source-tracking after a CLI deploy (which happens on the postdeploy hook on SDR).
One customer is getting the `multiple git error` iso-git failure on STL but the path errors don't show up in the CLI final error.
See this thread:
https://salesforce-internal.slack.com/archives/G02K6C90RBJ/p1711480148180689
@W-15347866@
errors in post retrieve/deploy get swallowed in mdTransfer catch block.
mdTransfer will include cause error data (if instanceof SfError) and actions.

fix: expand mdTransfer error

---

src/convert/convertContext/recompositionFinalizer.ts
src/convert/transformers/defaultMetadataTransformer.ts
src/resolve/metadataResolver.ts
src/resolve/sourceComponent.ts
src/utils/path.ts
test/snapshot/sampleProjects/legacySuffixSupport/__snapshots__/verify-md-files.expected/objects/LogEntryArchive__b.object
test/snapshot/sampleProjects/legacySuffixSupport/__snapshots__/verify-md-files.expected/package.xml
test/snapshot/sampleProjects/legacySuffixSupport/force-app/objects/objects/LogEntryArchive__b/LogEntryArchive__b.object-meta.xml
test/snapshot/sampleProjects/legacySuffixSupport/force-app/objects/objects/LogEntryArchive__b/fields/Timestamp__c.field-meta.xml
test/snapshot/sampleProjects/legacySuffixSupport/force-app/objects/objects/LogEntryArchive__b/fields/TransactionEntryNumber__c.field-meta.xml
test/snapshot/sampleProjects/legacySuffixSupport/force-app/objects/objects/LogEntryArchive__b/fields/TransactionId__c.field-meta.xml
test/snapshot/sampleProjects/legacySuffixSupport/force-app/objects/objects/LogEntryArchive__b/indexes/LogEntryArchiveIndex.indexe-meta.xml
test/snapshot/sampleProjects/legacySuffixSupport/sfdx-project.json
test/snapshot/sampleProjects/legacySuffixSupport/snapshots.test.ts
test/utils/path.test.ts

- adds a warning when people use the legacy `indexe` suffix to help speed migration
- restore backward compatibility support for `indexe`
https://github.com/forcedotcom/cli/issues/2847
[@W-15631183@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001qGSpPYAW/view)
QA: I was able to test this using https://github.com/jongpie/NebulaLogger/tree/8e6730e8fec1f287798e5c088c2a94cda1ba83bd/nebula-logger/plugins/big-object-archiving/plugin/objects/LogEntryArchive__b/indexes
using `convert source`

feat: warn about legacy suffix use

---

src/resolve/forceIgnore.ts

warn when user are ignoring everything in a retrieve (which brings stuff down inside `/unpackaged`) 
prevents the pain https://github.com/forcedotcom/cli/issues/2399 (just had another user hitting the same problem)
[@W-15667616@](https://gus.lightning.force.com/a07EE00001qX0WLYA0)

feat: warn about .forceignore and the unpackaged folder

---

src/collections/componentSetBuilder.ts
test/collections/componentSetBuilder.test.ts

handle a devOpsCenter followup to @W-15253267@

fix: md names handle spaces, colons, and both

---

src/client/metadataApiDeploy.ts
test/client/metadataApiDeploy.test.ts

if we don't have a component set, skip checking it against the server response
everything surrounding the method was on an iteration of the component set, this wasn't
https://github.com/forcedotcom/cli/issues/2862, @W-15735078@
doing a metadata deply/project report would result in incorrect warnings
no incorrect warnings

fix: if no component set to match against, skip checking server response

---

HANDBOOK.md
src/Presets.md
src/registry/variants.ts
test/snapshot/sampleProjects/preset-PermSet/sfdx-project.json
test/snapshot/sampleProjects/preset-decomposeLabels/sfdx-project.json
test/snapshot/sampleProjects/preset-sharingRules/sfdx-project.json
test/snapshot/sampleProjects/preset-workflow-mpd/sfdx-project.json
test/snapshot/sampleProjects/preset-workflow/sfdx-project.json

support the new name `sourceBehaviorOptions`
beta presest still work ok.  The change in forcedotcom schemas will help the few beta users migrate
@W-15792360@

feat: rename presets property

---

src/registry/metadataRegistry.json

We have created the new setup entities EnblProgramTaskSubCategory and LearningItemType and exposed them to mdApi.
Supports EnblProgramTaskSubCategory and LearningItemType entities in retrieve/deploy
The specified metadata type is unsupported: [EnblProgramTaskSubCategory] 
The specified metadata type is unsupported: [LearningItemType]
@W-15638748@
When we tried to retrieve this entity using sfdx commands getting the following error The specified metadata type is unsupported: [EnblProgramTaskSubCategory]. Same for the LearningItemType.

@W-15638748 | Changes to support EnblProgramTaskSubCategory and LearningItemType

---

src/collections/componentSetBuilder.ts
test/collections/componentSetBuilder.test.ts

`ComponentSet.forceIgnoredPaths` was not being set
it's now set

fix: set forceIgnoredPaths on CS

---

src/registry/metadataRegistry.json

Adds source tracking for metadata entity: StageDefinition
https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001r2EPCYA2/view
@W-15721482@
sfdx force:source commands did not work for StageDefinition metadata entity.
sfdx force:source commands should work for StageDefinition metadata entity.

chore: adding StageDefinition to the metadataRegistry

---

METADATA_SUPPORT.md
src/registry/metadataRegistry.json

…y or retrieve it explicilty
Remove ExpressionSetDefinitionVersion from metadataRegistry
https://gus.lightning.force.com/a07EE00001tKsmDYAS
User was able to retrieve or deploy ExpressionSetDefinitionVersion entity explicitly
User will not be able to retrieve or deploy ExpressionSetDefinitionVersion entity explicitly

fix: Remove ExpressionSetDefinitionVersion to not allow user to deploy it explicitly

---

test/snapshot/sampleProjects/singleCustomFieldRetrieve/snapshots.test.ts

test: only run the validationSourceDir once (avoid duplicate expects folders)

---

src/convert/convertContext/recompositionFinalizer.ts

multiple converters could be going on simultaneously, or as a long-lived process.  This cache hung around between converts and caused a bug for IDE.
see slack thread https://salesforce-internal.slack.com/archives/G0213NY8PMH/p1718754058826369
removing the cache was quite bad for perf https://github.com/forcedotcom/source-deploy-retrieve/actions/runs/9587973660
@W-15952068@

fix: class-scoped xml cache for recomposition

---

package.json
src/client/deployMessages.ts
src/client/metadataApiRetrieve.ts
src/client/types.ts
test/client/metadataApiDeploy.test.ts
test/client/metadataApiRetrieve.test.ts
yarn.lock

> really a type refactor; no intended functionality change for SDR
SDR is the source of FileResponse (and its subtype FileResponseSuccess).
All the real code that produces them provide a filepath, but the type has it as `?`.
consumers with strict TS have to do checks for no reason.
fixes part of https://github.com/forcedotcom/eslint-config-salesforce-typescript/actions/runs/9703130477/job/26780562510?pr=246#step:9:9
so I guess it's related to [@W-16116290@](https://gus.lightning.force.com/a07EE00001vThmcYAC)

feat: guarantee fileResponseSuccess has a path

---

src/registry/metadataRegistry.json
src/utils/collections.ts

Correct the metadata registry entry for DecisionMatrixDefinition.  Add DecisionMatrixDefinitionVersion and ExpressionSetDefinitionVersion.  It should be parent/child but the type's packaging code wasn't implemented that way.
@W-15489723@
https://github.com/forcedotcom/cli/issues/2823

fix: definition/version types 

---

package.json
src/resolve/sourceComponent.ts
test/resolve/sourceComponent.test.ts
yarn.lock

modifies the error message to give a possible hint to look at xml tags
adds UT
@W-11537212@
Error (1): Component conversion failed: Unable to find matching parent xml file for /Users/william.ruemmele/projects/scratches/dreamhouse-lwc/force-app/main/default/objects/Broker__c/validationRules/test.validationRule-meta.xml
Error (ConversionError): Component conversion failed: Invalid XML tags or unable to find matching parent xml file for ValidationRule "test"

fix: change error message, add UT

---

package.json
src/collections/componentSetBuilder.ts
src/convert/replacements.ts
yarn.lock

bump minimatch dependency to latest major version

fix: bump minimatch to latest major version

---

package.json
src/index.ts
src/registry/presets/presetMap.ts
src/registry/variants.ts
test/registry/presetTesting.ts
yarn.lock

the unspecified imports or file reads makes esbuild unable to bundle the modules. This PR fixes the issue that the presets json files are not bundled.
@W-16114122@
presets json modules are not able to be bundled without specifications, and results in the failure in extensions.
presets json modules are able to be bundled directly.

chore: use import rather than fs read

---

src/registry/metadataRegistry.json

Revert metadata registries for mlmodelartifact, mlmodelconnection and mlmodelschema top level components
@W-15020853@
Functionality Before:
Able to use CLI commands for deploying/retrieving ml-model metadata in test orgs ONLY.
Functionality After:
NOT able to use CLI commands for deploying/retrieving ml-model metadata anywhere.

@W-16265033 [MlModels] Revert some top-level types from metadata registry

---

package.json
src/client/metadataApiDeploy.ts
src/client/metadataTransfer.ts
src/collections/componentSetBuilder.ts
src/convert/convertContext/nonDecompositionFinalizer.ts
src/convert/convertContext/recompositionFinalizer.ts
src/convert/transformers/decomposedMetadataTransformer.ts
src/convert/transformers/defaultMetadataTransformer.ts
src/convert/transformers/staticResourceMetadataTransformer.ts
src/resolve/adapters/digitalExperienceSourceAdapter.ts
src/resolve/connectionResolver.ts
src/resolve/sourceComponent.ts
src/utils/filePathGenerator.ts
test/snapshot/sampleProjects/customLabels-multiple/snapshots.test.ts
yarn.lock

if it's logging/debug, insert some placeholder to indicate that it's not present
for values used in "real" code, preserve existing behavior.  Many of these are from inadequate types on the metadataRegistry (ex: DEB or StaticResource have a suffix, etc)
@ W-16116290@

fix: handle nulls/undefined in template literal

---

package.json
src/collections/componentSet.ts
src/convert/convertContext/recompositionFinalizer.ts
src/convert/transformers/decomposedMetadataTransformer.ts
src/convert/types.ts
src/registry/presets/decomposeWorkflowBeta.json
src/utils/decomposed.ts
test/collections/componentSet.test.ts
test/convert/convertContext/recomposition.test.ts
test/convert/transformers/decomposedMetadataTransformer.test.ts
test/mock/type-constants/customObjectConstantEmptyObjectMeta.ts
test/resolve/sourceComponent.test.ts
test/snapshot/sampleProjects/preset-workflow-mpd/__snapshots__/verify-md-files.expected/package.xml
test/snapshot/sampleProjects/preset-workflow/__snapshots__/verify-md-files.expected/package.xml
test/snapshot/sampleProjects/variant-workflow/__snapshots__/verify-md-files.expected/package.xml
test/snapshot/sampleProjects/variant-workflow/sfdx-project.json
yarn.lock

deploy -d of an entire folder including a blank CustomObject file causes the Object to be in the manifest.
Case 1: If the Object is in the manifest, the mdapi will validate that the Object metadata contains all the required fields.
Case 2: If the Object is not in the manifest (only one or more of its child types are) then the validation doesn't happen (only the child types are validated)
SDR, when generating the manifest, needs to ask if the top-level (ex: object.meta.xml) is effectively empty.  If so, that type should be omitted from the manifest (to get Case 2 behavior from the API)
update some tests that were based on an invalid mock
update the workflow preset to make all children of workflow unaddressable
@W-16273581@ (see inv)

fix: manifests for custom object can omit parent

---

src/convert/transformers/decomposedMetadataTransformer.ts
src/resolve/metadataResolver.ts
test/collections/componentSet.test.ts
test/resolve/metadataResolver.test.ts

sorts files/folders to folders first then files when searching for components so that we find everything
updates the cache when a parent with more information is found
https://github.com/forcedotcom/cli/issues/2230, @W-13629588@
would have to order modules alphabetically to get deploy to work
order doesn't matter

fix: recurse through dirs then files

---

contributing/metadata.md

Fixes formatting on the metadata markdown docs
Before:

chore: metadata md formatting

---

contributing/metadata.md
scripts/update-registry/describe.json
src/registry/metadataRegistry.json

Adds ExtlClntAppPushSettings and ExtlClntAppPushConfigurablePolicies metadata types.
Fixes a mistake in the instructions for adding new metadata types from cli-type-registry-info.json

fix: add ExtlClntAppPushSettings and ExtlClntAppPushConfigurablePolicies

---

src/client/metadataApiDeploy.ts
test/client/metadataApiDeploy.test.ts

Adds a warning when deploy size or deploy file count exceeds a threshold.  By default the threshold is 80% of the maximum MDAPI limit.
@W-16489032@
To QA:
export `DEBUG=sf:MetadataApiDeploy` and `SF_LOG_LEVEL=debug` to see debug output around deploy limits
deploy metadata to a scratch org (dreamhouse-lwc can be used as the project).  If you use the `--verbose` flag it will output the deploy size and count
Override the `SF_DEPLOY_SIZE_THRESHOLD` env var with different numbers to see changes.  100 or over will disable warnings.  0 will always show warnings.  In between, it depends on the amount of metadata being deployed.

feat: add deploy size and count warnings

---

.github/workflows/test.yml

removes plugin-source external NUTs
@W-17062306@

test: remove plugin-source ext NUTs

---

package.json

Force a new release. The `package.json` version got out of sync with the branch protection issues we had this week

fix: force new release

---

src/collections/componentSetBuilder.ts
src/resolve/metadataResolver.ts
test/resolve/metadataResolver.test.ts

Updates the metadata resolver to ignore XML files in a project that aren't part of a source component.
A customer had datapacks with an XML file that isn't part of the metadata inside `force_app`, when SDR built the component to deploy a specific metadata it would try to resolve the XML file as `emailservicesfunction` because the helpers to detect if a filepath was a metadata type were checking if the file suffix matched one in the registry (`emailservicesfunction.suffix === 'xml'`).
This PR updates `isMetadata` to first try to find the type based on the suffix, if it there's not then it will check for `strictDirectoryNames` type ones **and** their `directoryName`.
Repro:
1. create an invalid file in the project dir (force-app/main/default/lala/hehe.xml)
2. update forceignore to ignore …

fix(resolver): ignore non-component XML files in project

---

src/resolve/forceIgnore.ts
test/resolve/forceIgnore.test.ts

changes forceignore warnings to ignore commented lines
https://github.com/forcedotcom/cli/issues/3127
would warn on 
`# force-app\main`
will not warn on example above

chore: fix forceignore warnings on commented lines

---

package.json
src/collections/componentSetBuilder.ts
src/resolve/connectionResolver.ts
test/collections/componentSetBuilder.test.ts
test/resolve/connectionResolver.test.ts

Allows an include list of metadata types when building a manifest from an org.
Allows an exclude list of metadata types when building a manifest from an org.
Allows throttling of listMetadata API calls and queries when building a manifest from an org with the new `SF_LIST_METADATA_BATCH_SIZE` environment variable.
#3152
@W-17431548@

feat: support throttling of listMetadata calls and queries; include and exclude metadata

---

.github/workflows/supportedMetadataUpdate.yml

We had a few GHA failures because of a newline in the `LICENSE.md` file. This change only checks for changes in the `METADATA_SUPPORT.md` file before attempting to commit
Example failure:
https://github.com/forcedotcom/source-deploy-retrieve/actions/runs/12589411545/job/35089181629#step:9:17

Only check md file for changes

---

src/registry/metadataRegistry.json
src/registry/presets/decomposeWorkflowBeta.json

Updates the decomposed workflow preset to add the child type: Workflow Flow Actions
The overall metadata registry is also missing this child type so I'm adding it to that JSON as well.
In the current decomposed preset, Workflow Flow Actions are added to the `*.workflow-meta.xml` file instead of decomposed into their own directory and smaller files.
This is causing issues deploying decomposed workflow children, as Salesforce CLI appears to check the `*.workflow-meta.xml` file even when deploying just 1 decomposed workflow child like an email alert. Since the  `*.workflow-meta.xml`  isn't "empty", I'm unable to deploy just a decomposed WorkflowAlert for example.
Also, the "isAddressable: false" key in each supported decomposed workflow child is preventing each decomposed workflow child from …

fix: add workflow flow actions to decomposed workflow preset and allow isAddressable

---

src/resolve/metadataResolver.ts
test/resolve/metadataResolver.test.ts

Modifies the code when resolving potential metadata files to not reuse the suffixType when that type doesn't match with the provided file path.  Added a test to ensure this doesn't regress.
See the GitHub issue for a repro.  Certain metadata types have non-unique file suffixes like "rule" or "site".  These would not resolve correctly in certain code paths, such as when retrieving `RestrictionRule` metadata.
#3168
@W-17555689@

fix: resolve strict dirs before suffixes for potential metadata files

---

src/collections/componentSet.ts
test/collections/componentSet.test.ts

ensures the generated manifests are the same, when using `--post/pre` destructive changes or not
@W-17425220@
would NOT error when using `--post/pre` when a constructive manifest had a typo
would parse out typo (as it wasn't found locally) from the manifest sent to the server, and deployment would succeed
will send typo to server, and allow it to error there

fix: populate manifestComponents consistently

---

src/convert/convertContext/decomposedExternalServiceRegistrationFinalizer.ts
src/convert/transformers/decomposeExternalServiceRegistrationTransformer.ts
test/snapshot/sampleProjects/preset-decomposedESR/__snapshots__/verify-md-files.expected/externalServiceRegistrations/OpenAPIChallenge.externalServiceRegistration
test/snapshot/sampleProjects/preset-decomposedESR/__snapshots__/verify-source-files.expected/force-app/main/default/externalServiceRegistrations/OpenAPIChallenge.externalServiceRegistration-meta.xml
test/snapshot/sampleProjects/preset-decomposedESR/force-app/main/default/externalServiceRegistrations/OpenAPIChallenge.externalServiceRegistration-meta.xml
test/snapshot/sampleProjects/preset-decomposedESR/mdapiOutput/externalServiceRegistrations/OpenAPIChallenge.externalServiceRegistration
test/snapshot/sampleProjects/preset-decomposedESR/originalMdapi/externalServiceRegistrations/OpenAPIChallenge.externalServiceRegistration

chore: temp

---

package.json
src/collections/componentSetBuilder.ts
src/resolve/connectionResolver.ts
test/collections/componentSetBuilder.test.ts
yarn.lock

Allows ComponentSetBuilder to handle "pseudo-types", which are types that can be translated to one or more different metadata types.  At the moment, it can interpret "Agent" as a type.
Adds unit tests for the feature.
@W-17669669@

W-17669669: add pseudo-type support to ComponentSetBuilder

---

src/registry/metadataRegistry.json

This PR adds CLI metadata type support for AnnotationExtensionSet
@W-16815182@
Did not support .annotationextensionset and AnnotationExtensionSet metadata type
Support .annotationextensionset and AnnotationExtensionSet metadata type

fix: @W-16815182 - Add support for type AnnotationExtensionSet

---

src/registry/metadataRegistry.json

This PR updates the directory name for the _AnalyticsVisualization_ metadata type to `unified-analytics-visualization` and removes the _AnalyticsVizViewDef_ type from the registry.
https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000029W2yzYAC/view
@W-17791453@

feat(mdTypes): Update TUA Visualization Metadata Types

---

src/registry/metadataRegistry.json

This PR updates the directory names for the _AnalyticsVisualization_ and _AnalyticsWorkspace_ metadata types to align with the [recommendations](https://confluence.internal.salesforce.com/pages/viewpage.action?spaceKey=METADATA&title=Create+a+POJO+or+Java-Backed+Metadata+Type#:~:text=The%20standard%20is%20to%20use%20an%20init%2Dlower%2Dcased%2C%20plural%20version%20of%20the%20type%20name%2C%20which%20is%20why%20the%20Example%20type%20above%20specifies%20%22examples%22.) in the Metadata and Tooling API documentation.
Note: Since the TUA MDAPIs are not yet GA-released, this change will not impact any existing customers.
https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000029giuWYAQ/view
@W-17810143@

feat(mdTypes): Update TUA assets MD Types directory names

---

src/registry/metadataRegistry.json

Adds LifeSciConfigCategory and LifeSciConfigRecord entities to the SDR registry so that records can be deployed and retrieved through the SF CLI
[W-17803621](https://gus.lightning.force.com/a07EE000029d3IVYAY)
Could not deploy or retrieve LifeSciConfigCategory or LifeSciConfigRecord records
Can now deploy and retrieve LifeSciConfigCategory and LifeSciConfigRecord records

@W-17803621 Add LifeSciConfigCategory and LifeSciConfigRecord

---

src/registry/metadataRegistry.json

Rename AnnotationExtensionSet metadata type to InvocableActionExtension
Rename AnnotationExtensionSet metadata type to InvocableActionExtension after reviewing the entities with Data modeling team
#<Insert GitHub Issue>, @W-17936678@

fix: @W-17936678 - Rename AnnotationExtensionSet metadata type to InvocableActionExtension

---

src/resolve/pseudoTypes/agentResolver.ts

When plugins have API names that don't match the planner ID naming pattern, read the planner file to get the plugins.
@W-17909761@

W-17909761 - fix: resolve plugins from planner for agent pseudo type resolution

---

src/registry/metadataRegistry.json

It registers FieldServiceMobileConfig metadata type to SDR.
FieldServiceMobileConfig is GA in 256 and we also need to expose FieldServiceMobileConfig for DevOps center (API v64), For that we need to register our FieldServiceMobileConfig Metadata type to SDR
FieldServiceMobileConfig was not registered in SDR
FieldServiceMobileConfig will be registered in SDR

W-18115496 Regestring FieldServiceMobileConfig Metadata to SDR

---

package.json
src/client/metadataApiDeploy.ts
test/client/metadataApiDeploy.test.ts
test/mock/client/transferOperations.ts
yarn.lock

Modifies the call to jsForce's metadata.checkDeployStatus() to pass `isRestDeploy` to use the REST endpoint.
NOTE: This PR requires [this jsForce PR](https://github.com/jsforce/jsforce/pull/1670) to be merged and published.  Then the `@salesforce/core` library needs to be updated with the jsForce version that contains that PR.  Then this PR needs to bump to that version of `@salesforce/core`, and bump the dev-dep version of jsforce-node.  Then PDR needs to bump library versions to get all the changes.
@W-18012955@

W-18012955 - fix: add checkDeployStatus for REST

---

src/utils/filePathGenerator.ts

The file suffix should be genAiPlannerBundle not genAiPlanner
@W-18203471@

fix: suffix should be genAiPlannerBundle - W-18203471

---

src/collections/componentSetBuilder.ts
test/collections/componentSetBuilder.test.ts

Updates CSB build() method for when an Org and excluded types are passed in. It will check if the excluded type is a folder content and if so, it will also exclude the folder from the resulting CS. 
E.g. if Report type is excluded, it will also exclude ReportFolder.
[#3232](https://github.com/forcedotcom/cli/issues/3232), [@W-17980476@ >](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002AjRNfYAN/view)

W-17980476: exclude folder when folder content is excluded from org connection

---

src/client/metadataApiRetrieve.ts
src/client/types.ts
test/client/metadataApiRetrieve.test.ts
test/mock/client/transferOperations.ts

Adds support for the new, optional parameter on RetrieveRequest; `rootTypesWithDependencies`.  Using this parameter with an allowlisted metadata type (`Bot` is only supported as of today) will cause the response to include all dependent metadata for all requested metadata of that type.  It will also include a dependencies json file in a format similar to deploy/retrieve manifest xml files of the dependencies.
@W-17238293@

feat: add support for rootTypesWithDependencies to RetrieveRequest - W-17238293

---

package.json
src/collections/componentSet.ts
test/collections/componentSet.test.ts
test/snapshot/sampleProjects/customObjects-and-children/__snapshots__/verify-md-files-deploy.expected/deployOutput/mdapi/objects/Broker__c.object
test/snapshot/sampleProjects/customObjects-and-children/__snapshots__/verify-md-files-deploy.expected/deployOutput/mdapi/package.xml
test/snapshot/sampleProjects/customObjects-and-children/__snapshots__/verify-md-files-retrieve.expected/retrieveOutput/mdapi/objects/Broker__c.object
test/snapshot/sampleProjects/customObjects-and-children/__snapshots__/verify-md-files-retrieve.expected/retrieveOutput/mdapi/package.xml
test/snapshot/sampleProjects/customObjects-and-children/originalMdapi2/objects/Broker__c.object
test/snapshot/sampleProjects/customObjects-and-children/originalMdapi2/package.xml
test/snapshot/sampleProjects/customObjects-and-children/snapshots.test.ts
yarn.lock

When retrieving a `CustomObject` that has an empty object-meta.xml file, include the CustomObject in the manifest entry and not just custom fields or other children.  This does not affect deploying or converting since different behavior is required for those operation.  I.e., including a CustomObject in the manifest without the object-meta data would fail deployment validation.  See https://github.com/forcedotcom/source-deploy-retrieve/pull/1375
#3300, @W-18650723@
`sf project retrieve start -m CustomObject:TestObject__c` with an empty object-meta.xml file would result in a manifest like this:
```
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
<types>
<members>TestObject__c.TestField__c</members>
<name>CustomField</name>
</types>
<version>63.0</version>
</Package>
```
``` …
```

fix: include parent in manifest when retrieving - W-18650723

---

package.json
src/resolve/pseudoTypes/agentResolver.ts
test/collections/componentSetBuilder.test.ts
test/nuts/agents/agentResolver.test.ts
yarn.lock

Plugins created throw the UI don't follow the naming patter `p_{plannerId}_{pluginName}` for the DeveloperName. Therefore the query that fetches the **GenAiPluginDefinition** records filtering by DeveloperName like 'p_plannerId%' doesn't bring all plugins. 
Instead we have to query the **GenAiPlannerFunctionDef** junction table to get all plugins for a given plannerId.
[@W-18551485@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002EctR8YAJ/view)
[@W-18551440@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002Ecl3YYAR/view)
Query the **GenAiPluginDefinition** table to get the plugins filtering by DeveloperName like 'p_plannerId%'. This doesn't return the records that don't have the p_plannerId prefix.
Query the **GenAiPlannerFunctionDef** table to get all …

W-18551485: update agentResolver to get all customized geAiPlugins from the org

---

src/convert/replacements.ts
src/resolve/sourceComponent.ts
test/convert/replacements.test.ts

Updates the `ReplacementStream` transform stream to keep track of replacements applied to a file.
In the conversion pipeline we have this transformer perform [string replacements](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_ws_string_replace.htm) on each file.
Bigger files get split into chunks and could get into a false-positive about missing replacement when:
1. project specifies 2 or more string replacements in `sfdx-project.json`
2. big file is split in 2 or more chunks
3. 1st chunk contains 1 string to replace but the other one is in the next chunk
This is a false-positive warning because all chunks go through the transform step in the pipeline.
https://github.com/forcedotcom/cli/issues/3318 …

fix: track string replacements W-18794860

---

src/registry/metadataRegistry.json

This PR added ApiNamedQuery to metadataRegistry so that SF CLI could work with NamedQuery API features
This PR added ApiNamedQuery to metadataRegistry so that SF CLI could work with NamedQuery API features
#<Insert GitHub Issue>, @W-18141734@
SF CLI doesn't current support NamedQuery API features. An attempt to retrieve metadata type ApiNamedQuery will result in error "Error (RegistryError): Missing metadata type definition in registry for id 'apinamedquery'."
SF CLI supports interaction with ApiNamedQuery

@W-18141734: feat: add ApiNamedQuery to metadataRegistry

---

src/registry/metadataRegistry.json

add ExternalStoragePrvdConfig metadata type to the registry.
@W-18609786 https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002Ex2MUYAZ/view
NA
metadata type is exposed in registry.

@W-18609786 add new ExternalStoragePrvdConfig to metadata registry

---

src/convert/streams.ts

Add debug logger to detect hidden directories early
Github issue link: https://github.com/forcedotcom/cli/issues/3310, @W-18715150@
Hidden directory get processed normally
No early warning, no visibility
Catches all hidden directory usage and early detecting before writing

fix: add logger to detect hidden dir- W-18715150

---

METADATA_SUPPORT.md
src/registry/metadataRegistry.json

* Updates the Salesforce metadata registry to fix the `CatalogedApiArtifactVersionInfo` entry.  
* After a review, it was requested to rename `artfcsver` to `artifactsversion`; accordingly, this PR updates the name, directory, and suffix to match the new convention.
@W-19292248@
GUS Work Item: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002JqX0mYAF/view
The metadata registry entry for `CatalogedApiArtifactVersionInfo` used the outdated identifier `artfcsver`, along with the old directory and suffix.
The registry entry now uses the corrected identifier `artifactsversion` with updated directory and suffix, ensuring consistency with the revised naming standard.

@W-19292248@ Fix CatalogedApiArtifactVersionInfo in metadata registry

---

src/registry/metadataRegistry.json

Add McpServerDefinition metadata type to registry
N/A
@W-19742917@
McpServerDefinition metadata type is not in registry
McpServerDefinition metadata type is in registry

@W-19742917 add McpServerDefinition metadata type to registry
